var annotated_dup =
[
    [ "JUNO_APP_API_TAG", "structJUNO__APP__API__TAG.html", "structJUNO__APP__API__TAG" ],
    [ "JUNO_ASYNC_IO_API_TAG", "structJUNO__ASYNC__IO__API__TAG.html", "structJUNO__ASYNC__IO__API__TAG" ],
    [ "JUNO_BUFF_QUEUE_TAG", "structJUNO__BUFF__QUEUE__TAG.html", "structJUNO__BUFF__QUEUE__TAG" ],
    [ "JUNO_BUFF_STACK_TAG", "structJUNO__BUFF__STACK__TAG.html", "structJUNO__BUFF__STACK__TAG" ],
    [ "JUNO_HASH_API_TAG", "structJUNO__HASH__API__TAG.html", "structJUNO__HASH__API__TAG" ],
    [ "JUNO_I2C_IO_API_TAG", "structJUNO__I2C__IO__API__TAG.html", "structJUNO__I2C__IO__API__TAG" ],
    [ "JUNO_I2C_IO_MSG_HDR_TAG", "structJUNO__I2C__IO__MSG__HDR__TAG.html", "structJUNO__I2C__IO__MSG__HDR__TAG" ],
    [ "JUNO_I2C_IO_MSG_R_TAG", "structJUNO__I2C__IO__MSG__R__TAG.html", "structJUNO__I2C__IO__MSG__R__TAG" ],
    [ "JUNO_I2C_IO_MSG_TAG", "unionJUNO__I2C__IO__MSG__TAG.html", "unionJUNO__I2C__IO__MSG__TAG" ],
    [ "JUNO_I2C_IO_MSG_W_TAG", "structJUNO__I2C__IO__MSG__W__TAG.html", "structJUNO__I2C__IO__MSG__W__TAG" ],
    [ "JUNO_LOG_API_TAG", "structJUNO__LOG__API__TAG.html", "structJUNO__LOG__API__TAG" ],
    [ "JUNO_MAP_API_TAG", "structJUNO__MAP__API__TAG.html", "structJUNO__MAP__API__TAG" ],
    [ "JUNO_MATH_MAT_API_T", "structJUNO__MATH__MAT__API__T.html", "structJUNO__MATH__MAT__API__T" ],
    [ "JUNO_MEMORY_ALLOC_API_TAG", "structJUNO__MEMORY__ALLOC__API__TAG.html", "structJUNO__MEMORY__ALLOC__API__TAG" ],
    [ "JUNO_MEMORY_BLOCK_METADATA_TAG", "structJUNO__MEMORY__BLOCK__METADATA__TAG.html", "structJUNO__MEMORY__BLOCK__METADATA__TAG" ],
    [ "JUNO_MEMORY_TAG", "structJUNO__MEMORY__TAG.html", "structJUNO__MEMORY__TAG" ],
    [ "JUNO_MSG_API_TAG", "structJUNO__MSG__API__TAG.html", "structJUNO__MSG__API__TAG" ],
    [ "JUNO_MSG_BUFFER_TAG", "structJUNO__MSG__BUFFER__TAG.html", "structJUNO__MSG__BUFFER__TAG" ],
    [ "JUNO_PUBLISHER_API_TAG", "structJUNO__PUBLISHER__API__TAG.html", "structJUNO__PUBLISHER__API__TAG" ],
    [ "JUNO_SPI_IO_API_TAG", "structJUNO__SPI__IO__API__TAG.html", "structJUNO__SPI__IO__API__TAG" ],
    [ "JUNO_STRING_API_TAG", "structJUNO__STRING__API__TAG.html", "structJUNO__STRING__API__TAG" ],
    [ "JUNO_SUBSCRIBER_API_TAG", "structJUNO__SUBSCRIBER__API__TAG.html", "structJUNO__SUBSCRIBER__API__TAG" ],
    [ "JUNO_TIME_API_TAG", "structJUNO__TIME__API__TAG.html", "structJUNO__TIME__API__TAG" ],
    [ "JUNO_TIMESTAMP_TAG", "structJUNO__TIMESTAMP__TAG.html", "structJUNO__TIMESTAMP__TAG" ]
];