var hierarchy =
[
    [ "juno::ARRAY_T< T, N >", "structjuno_1_1ARRAY__T.html", null ],
    [ "ENGINE_CMD_MSG_TAG", "structENGINE__CMD__MSG__TAG.html", null ],
    [ "ENGINE_TLM_MSG_TAG", "structENGINE__TLM__MSG__TAG.html", null ],
    [ "JUNO_APP_API_TAG", "structJUNO__APP__API__TAG.html", null ],
    [ "JUNO_ASYNC_IO_API_TAG", "structJUNO__ASYNC__IO__API__TAG.html", null ],
    [ "JUNO_DS_ARRAY_API_TAG", "structJUNO__DS__ARRAY__API__TAG.html", null ],
    [ "JUNO_DS_HEAP_API_TAG", "structJUNO__DS__HEAP__API__TAG.html", null ],
    [ "JUNO_DS_HEAP_POINTER_API_TAG", "structJUNO__DS__HEAP__POINTER__API__TAG.html", null ],
    [ "JUNO_DS_QUEUE_API_TAG", "structJUNO__DS__QUEUE__API__TAG.html", null ],
    [ "JUNO_DS_STACK_API_TAG", "structJUNO__DS__STACK__API__TAG.html", null ],
    [ "JUNO_I2C_IO_API_TAG", "structJUNO__I2C__IO__API__TAG.html", null ],
    [ "JUNO_I2C_IO_MSG_HDR_TAG", "structJUNO__I2C__IO__MSG__HDR__TAG.html", null ],
    [ "JUNO_I2C_IO_MSG_R_TAG", "structJUNO__I2C__IO__MSG__R__TAG.html", null ],
    [ "JUNO_I2C_IO_MSG_TAG", "unionJUNO__I2C__IO__MSG__TAG.html", null ],
    [ "JUNO_I2C_IO_MSG_W_TAG", "structJUNO__I2C__IO__MSG__W__TAG.html", null ],
    [ "JUNO_LOG_API_TAG", "structJUNO__LOG__API__TAG.html", null ],
    [ "JUNO_M3X3_F32_TAG", "structJUNO__M3X3__F32__TAG.html", null ],
    [ "JUNO_M3X3_F64_TAG", "structJUNO__M3X3__F64__TAG.html", null ],
    [ "JUNO_M3X3_I32_TAG", "structJUNO__M3X3__I32__TAG.html", null ],
    [ "JUNO_M4X4_F32_TAG", "structJUNO__M4X4__F32__TAG.html", null ],
    [ "JUNO_M4X4_F64_TAG", "structJUNO__M4X4__F64__TAG.html", null ],
    [ "JUNO_M4X4_I32_TAG", "structJUNO__M4X4__I32__TAG.html", null ],
    [ "JUNO_MAP_API_TAG", "structJUNO__MAP__API__TAG.html", null ],
    [ "JUNO_MAP_HASHABLE_POINTER_API_TAG", "structJUNO__MAP__HASHABLE__POINTER__API__TAG.html", null ],
    [ "JUNO_MEMORY_ALLOC_API_TAG", "structJUNO__MEMORY__ALLOC__API__TAG.html", null ],
    [ "JUNO_MEMORY_BLOCK_METADATA_TAG", "structJUNO__MEMORY__BLOCK__METADATA__TAG.html", null ],
    [ "JUNO_MP_MTX_API_TAG", "structJUNO__MP__MTX__API__TAG.html", null ],
    [ "JUNO_POINTER_API_TAG", "structJUNO__POINTER__API__TAG.html", null ],
    [ "JUNO_RQUAT_F32_TAG", "unionJUNO__RQUAT__F32__TAG.html", null ],
    [ "JUNO_RQUAT_F64_TAG", "unionJUNO__RQUAT__F64__TAG.html", null ],
    [ "JUNO_RQUAT_I32_TAG", "unionJUNO__RQUAT__I32__TAG.html", null ],
    [ "JUNO_SB_BROKER_API_TAG", "structJUNO__SB__BROKER__API__TAG.html", null ],
    [ "JUNO_SCH_API_TAG", "structJUNO__SCH__API__TAG.html", null ],
    [ "JUNO_SM_STATE_API_TAG", "structJUNO__SM__STATE__API__TAG.html", null ],
    [ "JUNO_SPI_IO_API_TAG", "structJUNO__SPI__IO__API__TAG.html", null ],
    [ "JUNO_THREAD_API_TAG", "structJUNO__THREAD__API__TAG.html", null ],
    [ "JUNO_TIME_API_TAG", "structJUNO__TIME__API__TAG.html", null ],
    [ "JUNO_TIMESTAMP_TAG", "structJUNO__TIMESTAMP__TAG.html", null ],
    [ "JUNO_UDP_API_TAG", "structJUNO__UDP__API__TAG.html", null ],
    [ "JUNO_UDP_CFG_TAG", "structJUNO__UDP__CFG__TAG.html", null ],
    [ "JUNO_VALUE_POINTER_API_TAG", "structJUNO__VALUE__POINTER__API__TAG.html", null ],
    [ "JUNO_VEC2_F32_CART_TAG", "structJUNO__VEC2__F32__CART__TAG.html", null ],
    [ "JUNO_VEC2_F32_SPH_TAG", "structJUNO__VEC2__F32__SPH__TAG.html", null ],
    [ "JUNO_VEC2_F32_TAG", "unionJUNO__VEC2__F32__TAG.html", null ],
    [ "JUNO_VEC2_F64_CART_TAG", "structJUNO__VEC2__F64__CART__TAG.html", null ],
    [ "JUNO_VEC2_F64_SPH_TAG", "structJUNO__VEC2__F64__SPH__TAG.html", null ],
    [ "JUNO_VEC2_F64_TAG", "unionJUNO__VEC2__F64__TAG.html", null ],
    [ "JUNO_VEC2_I32_CART_TAG", "structJUNO__VEC2__I32__CART__TAG.html", null ],
    [ "JUNO_VEC2_I32_SPH_TAG", "structJUNO__VEC2__I32__SPH__TAG.html", null ],
    [ "JUNO_VEC2_I32_TAG", "unionJUNO__VEC2__I32__TAG.html", null ],
    [ "JUNO_VEC3_F32_CART_TAG", "structJUNO__VEC3__F32__CART__TAG.html", null ],
    [ "JUNO_VEC3_F32_SPH_TAG", "structJUNO__VEC3__F32__SPH__TAG.html", null ],
    [ "JUNO_VEC3_F32_TAG", "unionJUNO__VEC3__F32__TAG.html", null ],
    [ "JUNO_VEC3_F64_CART_TAG", "structJUNO__VEC3__F64__CART__TAG.html", null ],
    [ "JUNO_VEC3_F64_SPH_TAG", "structJUNO__VEC3__F64__SPH__TAG.html", null ],
    [ "JUNO_VEC3_F64_TAG", "unionJUNO__VEC3__F64__TAG.html", null ],
    [ "JUNO_VEC3_I32_CART_TAG", "structJUNO__VEC3__I32__CART__TAG.html", null ],
    [ "JUNO_VEC3_I32_SPH_TAG", "structJUNO__VEC3__I32__SPH__TAG.html", null ],
    [ "JUNO_VEC3_I32_TAG", "unionJUNO__VEC3__I32__TAG.html", null ],
    [ "JUNO_VEC4_F32_CART_TAG", "structJUNO__VEC4__F32__CART__TAG.html", null ],
    [ "JUNO_VEC4_F32_SPH_TAG", "structJUNO__VEC4__F32__SPH__TAG.html", null ],
    [ "JUNO_VEC4_F32_TAG", "unionJUNO__VEC4__F32__TAG.html", null ],
    [ "JUNO_VEC4_F64_CART_TAG", "structJUNO__VEC4__F64__CART__TAG.html", null ],
    [ "JUNO_VEC4_F64_SPH_TAG", "structJUNO__VEC4__F64__SPH__TAG.html", null ],
    [ "JUNO_VEC4_F64_TAG", "unionJUNO__VEC4__F64__TAG.html", null ],
    [ "JUNO_VEC4_I32_CART_TAG", "structJUNO__VEC4__I32__CART__TAG.html", null ],
    [ "JUNO_VEC4_I32_SPH_TAG", "structJUNO__VEC4__I32__SPH__TAG.html", null ],
    [ "JUNO_VEC4_I32_TAG", "unionJUNO__VEC4__I32__TAG.html", null ],
    [ "juno::OPTION_T< T >", "structjuno_1_1OPTION__T.html", null ],
    [ "juno::buff::QUEUE_API_T< T, N >", "structjuno_1_1buff_1_1QUEUE__API__T.html", null ],
    [ "juno::RESULT_T< T >", "structjuno_1_1RESULT__T.html", null ],
    [ "juno::RESULT_T< T * >", "structjuno_1_1RESULT__T.html", null ],
    [ "juno::buff::STACK_API_T< T, N >", "structjuno_1_1buff_1_1STACK__API__T.html", null ],
    [ "testing::Test", null, [
      [ "MonitorAppTest", "classMonitorAppTest.html", null ],
      [ "ProcessorAppTest", "classProcessorAppTest.html", null ],
      [ "SenderAppTest", "classSenderAppTest.html", null ],
      [ "ThreadModuleTest", "classThreadModuleTest.html", null ],
      [ "UdpBridgeAppTest", "classUdpBridgeAppTest.html", null ],
      [ "UdpModuleTest", "classUdpModuleTest.html", null ]
    ] ],
    [ "UDP_THREAD_MSG_TAG", "structUDP__THREAD__MSG__TAG.html", null ],
    [ "USER_DATA_T", "structUSER__DATA__T.html", null ]
];