/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_msg library API
    @author Robin Onsay
*/
#ifndef JUNO_BROKER_API_H
#define JUNO_BROKER_API_H
#include "juno/memory/memory_api.h"
#include "juno/status.h"
#include "juno/module.h"
#include <stdio.h>
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_BROKER_API_TAG JUNO_BROKER_API_T;
typedef struct JUNO_MSG_BUFFER_HDR_TAG JUNO_MSG_BUFFER_HDR_T;

typedef union JUNO_MSG_TAG JUNO_MSG_T;
typedef struct JUNO_MSG_ROOT_TAG JUNO_MSG_ROOT_T;

struct JUNO_MSG_BUFFER_HDR_TAG
{
    JUNO_MSG_BUFFER_HDR_T *ptNext;
    size_t zBufferSize;
};

/// Creates a new buffer
#define JunoMsg_NewBuffer(BUFFER_T, ...)  {{NULL, sizeof(BUFFER_T)}, __VA_ARGS__}

struct JUNO_MSG_ROOT_TAG JUNO_MODULE_ROOT(JUNO_BROKER_API_T,
    JUNO_MEMORY_ALLOC_T *ptAlloc;
);

struct JUNO_BROKER_API_TAG
{
    /// Verify the message
    JUNO_STATUS_T (*VerifyMsg)(JUNO_MSG_T *ptJunoMsg);
    /// Get the message buffer
    JUNO_STATUS_T (*GetBuffer)(JUNO_MSG_T *ptJunoMsg, const JUNO_MSG_BUFFER_HDR_T *ptRetBuffer);
    /// Set the message buffer
    JUNO_STATUS_T (*SetBuffer)(JUNO_MSG_T *ptJunoMsg, const JUNO_MSG_BUFFER_HDR_T tRetBuffer);
};

#ifdef __cplusplus
}
#endif
#endif // JUNO_BROKER_API_H
