/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    @file include/juno/broker/broker_api.h
    @brief This file contains the implementation of the Software Bus (SB) Broker.
    The main purpose of the broker is to distribute software bus messages between
    various applications **within a single thread**. Various applications could be
    running on a processor within a thread and the broker offers a methodology
    of distributing the messages to the applications.

    The broker **IS NOT** thread safe by design. The rationale for this design decision
    is to encourage the handling of IPC to be on the software architect. It's up to them
    to determine how multiple threads will communicate with each other since they are the
    experts of their software system. This design paradigm encourages
    "share data not memory" and gives software architects the option to implement
    whichever IPC mechanism they would like (i.e. UDP/TCP, POSIX queues, In-memory buffers, etc).
    @author Robin Onsay
 */
#ifndef JUNO_SB_API_H
#define JUNO_SB_API_H
#include "juno/ds/array_api.h"
#include "juno/macros.h"
#include "juno/memory/pointer_api.h"
#include "juno/status.h"
#include "juno/module.h"
#include "juno/ds/buff_queue_api.h"
#include <stddef.h>
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_SB_BROKER_ROOT_TAG JUNO_SB_BROKER_ROOT_T;
typedef struct JUNO_SB_BROKER_API_TAG JUNO_SB_BROKER_API_T;
typedef struct JUNO_SB_PIPE_REGISTRY_TAG JUNO_SB_PIPE_REGISTRY_T;
typedef struct JUNO_SB_PIPE_TAG JUNO_SB_PIPE_T;

struct JUNO_SB_PIPE_TAG
{
    /// The recv queue of the pipe
    JUNO_DS_QUEUE_ROOT_T *ptRecvQueue;
    /// The mid the pipe is subscribed to
    JUNO_VALUE_POINTER_T tMid;
};

struct JUNO_SB_PIPE_REGISTRY_TAG JUNO_MODULE_DERIVE(JUNO_DS_ARRAY_ROOT_T,
    /// Array of receive queue buffer pointers
    JUNO_SB_PIPE_T *ptArrItems;
    size_t zLength;
);

struct JUNO_SB_BROKER_ROOT_TAG JUNO_MODULE_ROOT(JUNO_SB_BROKER_API_T,
    /// Pointer to the broker registry
    JUNO_SB_PIPE_REGISTRY_T *ptRegistry;
);

struct JUNO_SB_BROKER_API_TAG
{
    /// Publish a message using the broker
    JUNO_STATUS_T (*Publish)(JUNO_SB_BROKER_ROOT_T *ptBroker, JUNO_VALUE_POINTER_T tMid, JUNO_POINTER_T tMsg);
    /// Subscribe to a message through the broker
    JUNO_STATUS_T (*RegisterSubscriber)(JUNO_SB_BROKER_ROOT_T *ptBroker, JUNO_SB_PIPE_T *ptPipe);
};

static inline JUNO_STATUS_T JunoSb_BrokerApiVerify(const JUNO_SB_BROKER_API_T *ptBrokerApi)
{
    JUNO_ASSERT_EXISTS(
        ptBrokerApi &&
        ptBrokerApi->Publish &&
        ptBrokerApi->RegisterSubscriber
    );
    return JUNO_STATUS_SUCCESS;
}

static inline JUNO_STATUS_T JunoSb_RegistryVerify(const JUNO_SB_PIPE_REGISTRY_T *ptRegistry)
{
    JUNO_ASSERT_EXISTS(ptRegistry && ptRegistry->ptArrItems);
    JUNO_STATUS_T tStatus = JunoDs_ArrayVerify(&ptRegistry->tRoot);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return tStatus;
}

static inline JUNO_STATUS_T JunoSb_BrokerVerify(const JUNO_SB_BROKER_ROOT_T *ptBroker)
{
    JUNO_STATUS_T tStatus = JUNO_STATUS_SUCCESS;
    JUNO_ASSERT_EXISTS(ptBroker);
    tStatus = JunoSb_BrokerApiVerify(ptBroker->ptApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    JUNO_ASSERT_EXISTS(ptBroker->ptRegistry);
    tStatus = JunoSb_RegistryVerify(ptBroker->ptRegistry);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return tStatus;
}

static inline JUNO_STATUS_T JunoSb_PipeVerify(const JUNO_SB_PIPE_T *ptPipe)
{
    JUNO_ASSERT_EXISTS(ptPipe);
    JUNO_STATUS_T tStatus = JunoDs_Buff_QueueVerify(ptPipe->ptRecvQueue);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    tStatus = JunoMemory_ValuePointerApiVerify(ptPipe->tMid.ptApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return tStatus;
}

JUNO_STATUS_T JunoSb_RegistryInit(JUNO_SB_PIPE_REGISTRY_T *ptRegistry, JUNO_SB_PIPE_T *ptArrRecvQueues, const size_t iCapacity);
JUNO_STATUS_T JunoSb_BrokerInit(JUNO_SB_BROKER_ROOT_T *ptBroker, JUNO_SB_PIPE_REGISTRY_T *ptRegistry);


#ifdef __cplusplus
}
#endif
#endif // JUNO_SB_API_H
