/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
 * @file include/juno/sb/msg_api.h
 * @brief Juno message abstraction API.
 * @author Robin Onsay
 */
#ifndef JUNO_MSG_API_H
#define JUNO_MSG_API_H
#include "juno/status.h"
#include "juno/module.h"
#include "juno/ds/buff_queue_api.h"
#include <stdio.h>
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_MSG_QUEUE_API_TAG JUNO_MSG_QUEUE_API_T;
typedef struct JUNO_MSG_QUEUE_ROOT_TAG JUNO_MSG_QUEUE_ROOT_T;

struct JUNO_MSG_QUEUE_ROOT_TAG JUNO_MODULE_DERIVE(JUNO_BUFF_QUEUE_ROOT_T,
);

struct JUNO_MSG_QUEUE_API_TAG JUNO_MODULE_API_DERIVE(JUNO_BUFF_QUEUE_API_T,
    /// Gets the unique id of this msg type
    JUNO_RESULT_VOID_PTR_T (*GetMsgQueueUid)(JUNO_MSG_QUEUE_ROOT_T *ptJunoMsg);
);

#ifdef __cplusplus
}
#endif
#endif // JUNO_MSG_API_H
