/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_msg library API
    @author
*/
#ifndef JUNO_MSG_API_H
#define JUNO_MSG_API_H
#include "juno/status.h"
#include "juno/module.h"
#include <stdio.h>
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_MSG_API_TAG JUNO_MSG_API_T;
typedef struct JUNO_MSG_BUFFER_TAG JUNO_MSG_BUFFER_T;

JUNO_MODULE_DECLARE(JUNO_MSG_T);
JUNO_MODULE_BASE_DECLARE(JUNO_MSG_BASE_T);

struct JUNO_MSG_BUFFER_TAG
{
    void *pvBuffer;
    size_t zBufferSize;
};

JUNO_MODULE_BASE(JUNO_MSG_BASE_T, JUNO_MSG_API_T,
    JUNO_MSG_BUFFER_T *ptBuffer;
);

struct JUNO_MSG_API_TAG
{
    /// Verify the message
    JUNO_STATUS_T (*VerifyMsg)(JUNO_MSG_T *ptJunoMsg);
    /// Get the message buffer
    JUNO_STATUS_T (*GetBuffer)(JUNO_MSG_T *ptJunoMsg, JUNO_MSG_BUFFER_T *ptRetBuffer);
    /// Set the message buffer
    JUNO_STATUS_T (*SetBuffer)(JUNO_MSG_T *ptJunoMsg, JUNO_MSG_BUFFER_T tRetBuffer);
};

#ifdef __cplusplus
}
#endif
#endif // JUNO_MSG_API_H
