var searchData=
[
  ['h_0',['h',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2example__project_2LibJuno__Tutorial.html#autotoc_md87',1,'engine_app.h'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2example__project_2LibJuno__Tutorial.html#autotoc_md92',1,'engine_cmd_msg.h']]],
  ['h_20tt_1',['h tt',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2design_202-udp-module.html#autotoc_md184',1,'Forbidden includes in &lt;tt&gt;udp_api.h&lt;/tt&gt;'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2design_202-udp-module.html#autotoc_md183',1,'Permitted includes in &lt;tt&gt;udp_api.h&lt;/tt&gt;']]],
  ['handler_2',['handler',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2test-cases_202-thread-module.html#autotoc_md333',1,'Error Status and Failure Handler'],['../main_8c.html#autotoc_md114',1,'Failure Handler'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2example__project_2LibJuno__Tutorial.html#autotoc_md82',1,'Failure Handler'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2test-cases_201-udp-module.html#autotoc_md264',1,'TC-UDP-002 — Init with null root returns error and invokes failure handler'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2test-cases_201-udp-module.html#autotoc_md266',1,'TC-UDP-003 — Init with null vtable returns error and invokes failure handler'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2test-cases_201-udp-module.html#autotoc_md285',1,'TC-UDP-011 — Send with null message pointer returns error and invokes failure handler'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2test-cases_201-udp-module.html#autotoc_md292',1,'TC-UDP-014 — Receive with null output pointer returns error and invokes failure handler']]],
  ['handler_20and_20returns_20error_3',['handler and returns error',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2test-cases_202-thread-module.html#autotoc_md312',1,'TC-THREAD-002 — Init with null root invokes failure handler and returns error'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2test-cases_202-thread-module.html#autotoc_md314',1,'TC-THREAD-003 — Init with null vtable invokes failure handler and returns error']]],
  ['handler_20invocation_4',['TC-THREAD-011 — Failed pthread_create causes failure handler invocation',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2test-cases_202-thread-module.html#autotoc_md334',1,'']]],
  ['handler_20req_20udp_20012_20req_20udp_20013_5',['Test Cases: Error Status Return and Failure Handler (REQ-UDP-012, REQ-UDP-013)',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2test-cases_201-udp-module.html#autotoc_md299',1,'']]],
  ['handler_20with_20non_20null_20user_20data_6',['TC-UDP-018 — Failed open due to bad address invokes failure handler with non-null user data',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2test-cases_201-udp-module.html#autotoc_md302',1,'']]],
  ['handling_7',['handling',['../md__2home_2runner_2work_2libjuno_2libjuno_2include_2juno_2memory_2README.html#autotoc_md19',1,'Error Handling'],['../md__2home_2runner_2work_2libjuno_2libjuno_2include_2juno_2README.html#autotoc_md34',1,'Status and Error Handling'],['../group__juno__status.html',1,'Status and error handling']]],
  ['handling_20strategy_8',['handling strategy',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2design_202-udp-module.html#autotoc_md180',1,'3.5 Error Handling Strategy'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2design_203-thread-module.html#autotoc_md204',1,'4.6 Error Handling Strategy']]],
  ['hash_9',['Hash',['../structJUNO__MAP__HASHABLE__POINTER__API__TAG.html#aded0c2fc42482d65809db1a9af6a4f76',1,'JUNO_MAP_HASHABLE_POINTER_API_TAG']]],
  ['hash_20utilities_10',['Hash Utilities',['../group__juno__hash.html',1,'']]],
  ['hash_5fdjb2_2eh_11',['hash_djb2.h',['../hash__djb2_8h.html',1,'']]],
  ['header_20constraints_12',['header constraints',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2design_202-udp-module.html#autotoc_md182',1,'3.6 Interface Header Constraints'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2udp-threads_2docs_2design_203-thread-module.html#autotoc_md206',1,'4.7 Interface Header Constraints']]],
  ['headers_13',['Core types (public headers)',['../md__2home_2runner_2work_2libjuno_2libjuno_2include_2juno_2memory_2README.html#autotoc_md2',1,'']]],
  ['heap_20api_14',['Heap API',['../group__juno__ds__heap.html',1,'']]],
  ['heap_5fapi_2eh_15',['heap_api.h',['../heap__api_8h.html',1,'']]],
  ['heapify_16',['Heapify',['../structJUNO__DS__HEAP__API__TAG.html#a77047c846432b278a0f1f3dfd66c4431',1,'JUNO_DS_HEAP_API_TAG']]],
  ['helpers_17',['Assertions and helpers',['../group__juno__macros.html',1,'']]],
  ['helpers_20provided_20by_20the_20api_18',['Helpers provided by the API',['../md__2home_2runner_2work_2libjuno_2libjuno_2include_2juno_2memory_2README.html#autotoc_md11',1,'']]],
  ['href_20https_3a_20marketplace_20visualstudio_20com_20items_20itemname_20robinonsay_20libjuno_20vscode_20extension_20a_20—_20navigate_20dependency_20injection_20like_20magic_19',['&lt;strong&gt;NEW&lt;/strong&gt; &lt;a href=&quot;https://marketplace.visualstudio.com/items?itemName=RobinOnsay.libjuno&quot; &gt;VSCode Extension&lt;/a&gt; — Navigate Dependency Injection Like Magic',['../index.html#autotoc_md41',1,'']]],
  ['https_3a_20marketplace_20visualstudio_20com_20items_20itemname_20robinonsay_20libjuno_20vscode_20extension_20a_20—_20navigate_20dependency_20injection_20like_20magic_20',['&lt;strong&gt;NEW&lt;/strong&gt; &lt;a href=&quot;https://marketplace.visualstudio.com/items?itemName=RobinOnsay.libjuno&quot; &gt;VSCode Extension&lt;/a&gt; — Navigate Dependency Injection Like Magic',['../index.html#autotoc_md41',1,'']]]
];
