var searchData=
[
  ['c_0',['c',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2example__project_2LibJuno__Tutorial.html#autotoc_md100',1,'engine_app.c'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2example__project_2LibJuno__Tutorial.html#autotoc_md93',1,'engine_cmd_msg.c'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2example__project_2LibJuno__Tutorial.html#autotoc_md76',1,'main.c'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2example__project_2LibJuno__Tutorial.html#autotoc_md107',1,'system_manager_app.c']]],
  ['c_20tt_1',['c tt',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2README.html#autotoc_md124',1,'1. Minimal Memory Example (&lt;tt&gt;minimal_memory_example.c&lt;/tt&gt;)'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2README.html#autotoc_md126',1,'2. Minimal Queue Example (&lt;tt&gt;minimal_queue_example.c&lt;/tt&gt;)'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2README.html#autotoc_md128',1,'3. State Machine Example (&lt;tt&gt;example_state_machine.c&lt;/tt&gt;)']]],
  ['ccitt_2eh_2',['ccitt.h',['../ccitt_8h.html',1,'']]],
  ['ccitt32_2eh_3',['ccitt32.h',['../ccitt32_8h.html',1,'']]],
  ['ccitt32_5fcrctab_4',['ccitt32_crctab',['../ccitt32_8h.html#a12bcb63f4f848657c587d9d97da5924b',1,'ccitt32.h']]],
  ['ccitt_5fcrctab_5',['ccitt_crctab',['../ccitt_8h.html#a2e7b36ec015747581fcb47444825cd31',1,'ccitt.h']]],
  ['cmake_20build_20options_6',['CMake Build Options',['../index.html#autotoc_md51',1,'']]],
  ['code_20generation_20scripts_7',['Code Generation Scripts',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2README.html#autotoc_md134',1,'']]],
  ['code_20style_8',['Example Code Style',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2README.html#autotoc_md135',1,'']]],
  ['codes_9',['Status codes',['../group__juno__status__codes.html',1,'']]],
  ['command_20pipe_10',['command pipe',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2example__project_2LibJuno__Tutorial.html#autotoc_md92',1,'Engine Command Pipe'],['../engine__cmd__msg_8h.html#autotoc_md62',1,'Engine Command Pipe']]],
  ['command_20pipe_20implementation_11',['command pipe implementation',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2example__project_2LibJuno__Tutorial.html#autotoc_md94',1,'Engine Command Pipe Implementation'],['../engine__cmd__msg_8c.html#autotoc_md69',1,'Engine Command Pipe Implementation']]],
  ['commands_12',['commands',['../engine__cmd__msg_8h.html#autotoc_md61',1,'Engine Application Commands'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2example__project_2LibJuno__Tutorial.html#autotoc_md91',1,'Engine Application Commands']]],
  ['common_20pitfalls_13',['Common pitfalls',['../md__2home_2runner_2work_2libjuno_2libjuno_2include_2juno_2memory_2README.html#autotoc_md16',1,'']]],
  ['common_20result_20types_14',['Common result types',['../group__juno__types.html',1,'']]],
  ['compare_15',['Compare',['../structJUNO__DS__HEAP__POINTER__API__TAG.html#acca159751a6cc543ef2184ec11c72660',1,'JUNO_DS_HEAP_POINTER_API_TAG']]],
  ['compatibility_16',['Freestanding Compatibility',['../md__2home_2runner_2work_2libjuno_2libjuno_2include_2juno_2README.html#autotoc_md35',1,'']]],
  ['compiles_20like_20the_20tests_17',['Minimal end-to-end example (compiles like the tests)',['../md__2home_2runner_2work_2libjuno_2libjuno_2include_2juno_2memory_2README.html#autotoc_md17',1,'']]],
  ['complete_20tutorial_20project_20tt_20example_5fproject_20tt_18',['4. Complete Tutorial Project (&lt;tt&gt;example_project/&lt;/tt&gt;)',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2README.html#autotoc_md130',1,'']]],
  ['concepts_19',['Core Concepts',['../md__2home_2runner_2work_2libjuno_2libjuno_2include_2juno_2README.html#autotoc_md24',1,'']]],
  ['conclusion_20',['conclusion',['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2example__project_2LibJuno__Tutorial.html#autotoc_md108',1,'Conclusion'],['../system__manager__app_8c.html#autotoc_md117',1,'Conclusion']]],
  ['contributing_21',['Contributing',['../index.html#autotoc_md55',1,'']]],
  ['convenience_20macros_22',['Typed convenience macros',['../md__2home_2runner_2work_2libjuno_2libjuno_2include_2juno_2memory_2README.html#autotoc_md14',1,'']]],
  ['copy_23',['copy',['../structJUNO__POINTER__API__TAG.html#af21d37354b6c96fdeef8a6c824012686',1,'JUNO_POINTER_API_TAG::Copy'],['../engine__cmd__msg_8c.html#autotoc_md70',1,'Pointer Copy'],['../md__2home_2runner_2work_2libjuno_2libjuno_2examples_2example__project_2LibJuno__Tutorial.html#autotoc_md95',1,'Pointer Copy']]],
  ['copy_20and_20reset_24',['Pointer API (Copy and Reset)',['../md__2home_2runner_2work_2libjuno_2libjuno_2include_2juno_2memory_2README.html#autotoc_md10',1,'']]],
  ['core_25',['Math Core',['../group__juno__math.html',1,'']]],
  ['core_20concepts_26',['Core Concepts',['../md__2home_2runner_2work_2libjuno_2libjuno_2include_2juno_2README.html#autotoc_md24',1,'']]],
  ['core_20philosophy_27',['Core Philosophy',['../index.html#autotoc_md42',1,'']]],
  ['core_20types_20public_20headers_28',['Core types (public headers)',['../md__2home_2runner_2work_2libjuno_2libjuno_2include_2juno_2memory_2README.html#autotoc_md2',1,'']]],
  ['crc_20utilities_29',['CRC utilities',['../group__juno__crc.html',1,'']]],
  ['crc_2eh_30',['crc.h',['../crc_8h.html',1,'']]]
];
