/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
 * @file memory_api.h
 * @brief Abstract memory allocation API and verification helpers.
 * @defgroup juno_memory_alloc Memory allocation API
 * @details
 *  Provides a generic allocation interface that concrete allocators implement
 *  (e.g., fixed block allocator). The API is freestanding-friendly and uses
 *  JUNO_POINTER_T descriptors for memory regions.
 */
#ifndef JUNO_MEMORY_API_H
#define JUNO_MEMORY_API_H
#include "juno/macros.h"
#include "juno/status.h"
#include "juno/module.h"
#include <stddef.h>
#include <stdalign.h>
#include "juno/memory/pointer_api.h"
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_MEMORY_ALLOC_API_TAG JUNO_MEMORY_ALLOC_API_T;
typedef struct JUNO_MEMORY_ALLOC_ROOT_TAG JUNO_MEMORY_ALLOC_ROOT_T;

struct JUNO_MEMORY_ALLOC_ROOT_TAG JUNO_MODULE_ROOT(JUNO_MEMORY_ALLOC_API_T,
    const JUNO_POINTER_API_T *ptPointerApi;
);

/** @brief Vtable for memory allocation operations.
 *  @ingroup juno_memory_alloc
 */
struct JUNO_MEMORY_ALLOC_API_TAG
{
    /// @brief Allocate a memory region of at least zSize bytes.
    /// @param ptMem Allocator root object.
    /// @param zSize Size in bytes to allocate.
    /// @return Result containing a JUNO_POINTER_T on success.
    JUNO_RESULT_POINTER_T (*Get)(JUNO_MEMORY_ALLOC_ROOT_T *ptMem, size_t zSize);

    /// @brief Update an existing allocation to a new size.
    /// @param ptMem Allocator root object.
    /// @param ptMemory Pointer descriptor to update (in/out).
    /// @param zNewSize The new size in bytes.
    /// @return JUNO_STATUS_SUCCESS on success, error code otherwise.
    JUNO_STATUS_T (*Update)(JUNO_MEMORY_ALLOC_ROOT_T *ptMem, JUNO_POINTER_T *ptMemory, size_t zNewSize);

    /// @brief Free a previously allocated memory region.
    /// @param ptMem Allocator root object.
    /// @param pvAddr Pointer descriptor to free.
    /// @return JUNO_STATUS_SUCCESS on success, error code otherwise.
    JUNO_STATUS_T (*Put)(JUNO_MEMORY_ALLOC_ROOT_T *ptMem, JUNO_POINTER_T *pvAddr);
};

/**
 * @brief Verify that a memory allocator API provides required functions.
 * @param ptAllocApi API vtable to check.
 * @return JUNO_STATUS_SUCCESS if valid.
 */
/**
 * @brief Verify that a memory allocator API provides required functions.
 * @ingroup juno_memory_alloc
 * @param ptAllocApi API vtable to check.
 * @return JUNO_STATUS_SUCCESS if valid; error otherwise.
 */
static inline JUNO_STATUS_T JunoMemory_AllocApiVerify(const JUNO_MEMORY_ALLOC_API_T *ptAllocApi)
{
    JUNO_ASSERT_EXISTS(
        ptAllocApi &&
        ptAllocApi->Get &&
        ptAllocApi->Put &&
        ptAllocApi->Update
    );
    return JUNO_STATUS_SUCCESS;
}

/**
 * @brief Verify a memory allocator instance and its dependent pointer API.
 * @param ptAlloc Allocator root object to verify.
 * @return JUNO_STATUS_SUCCESS if valid; error otherwise.
 */
/**
 * @brief Verify a memory allocator instance and its dependent pointer API.
 * @ingroup juno_memory_alloc
 * @param ptAlloc Allocator root object to verify.
 * @return JUNO_STATUS_SUCCESS if valid; error otherwise.
 */
static inline JUNO_STATUS_T JunoMemory_AllocVerify(const JUNO_MEMORY_ALLOC_ROOT_T *ptAlloc)
{
    JUNO_ASSERT_EXISTS(
        ptAlloc &&
        ptAlloc->ptApi &&
        ptAlloc->ptPointerApi
    );
    JUNO_STATUS_T tStatus = JunoMemory_AllocApiVerify(ptAlloc->ptApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    tStatus = JunoMemory_PointerApiVerify(ptAlloc->ptPointerApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return tStatus;
}

#ifdef __cplusplus
}
#endif
#endif // JUNO_MEMORY_API_H
