/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_memory library API
    @author Robin Onsay
*/
#ifndef JUNO_MEMORY_API_H
#define JUNO_MEMORY_API_H
#include "juno/macros.h"
#include "juno/status.h"
#include "juno/module.h"
#include <stddef.h>
#include <stdalign.h>
#ifdef __cplusplus
extern "C"
{
#endif
/// Define a reference for memory
#define JUNO_REF(name) REF##name
/// Create a new reference for memory
#define JUNO_NEW_REF(name) JUNO_POINTER_T *JUNO_REF(name)

typedef struct JUNO_POINTER_TAG JUNO_POINTER_T;
typedef struct JUNO_POINTER_API_TAG JUNO_POINTER_API_T;
typedef struct JUNO_MEMORY_ALLOC_API_TAG JUNO_MEMORY_ALLOC_API_T;
typedef struct JUNO_MEMORY_ALLOC_ROOT_TAG JUNO_MEMORY_ALLOC_ROOT_T;

/// The memory metadata
struct JUNO_MEMORY_BLOCK_METADATA_TAG
{
    uint8_t *ptFreeMem;
};

/// @brief Structure for an allocated memory segment.
/// Describes the allocated memory with a pointer to the start and its size.
struct JUNO_POINTER_TAG JUNO_MODULE_LITE_ROOT(JUNO_POINTER_API_T,
    /// Pointer to the allocated memory.
    void *pvAddr;
    /// Size of the allocated memory, in bytes.
    size_t zSize;
    size_t zAlignment;
);

#define Juno_PointerInit(api, type, addr) (JUNO_POINTER_T){api, addr, sizeof(type), alignof(type)}
#define JUNO_CHECK_POINTER_TYPE(pointer, type) ((pointer.zSize == sizeof(type) && (uintptr_t) pointer.pvAddr % pointer.zAlignment == 0)?JUNO_STATUS_SUCCESS:JUNO_STATUS_ERR)

struct JUNO_POINTER_API_TAG
{
    /// Copy memory from one pointer to another
    JUNO_STATUS_T (*Copy)(JUNO_POINTER_T tDest, JUNO_POINTER_T tSrc);
    /// Reset the memory at the pointer. This could mean zero-initialization
    JUNO_STATUS_T (*Reset)(JUNO_POINTER_T tPointer);
};

JUNO_MODULE_RESULT(JUNO_RESULT_POINTER_T, JUNO_POINTER_T);

struct JUNO_MEMORY_ALLOC_ROOT_TAG JUNO_MODULE_ROOT(JUNO_MEMORY_ALLOC_API_T,
    const JUNO_POINTER_API_T *ptPointerApi;
);

struct JUNO_MEMORY_ALLOC_API_TAG
{
    /// @brief Allocates memory using the specified memory allocation method.
    /// 
    /// @param ptMem Pointer to the memory allocation structure.
    /// @param pvRetAddr Pointer to a memory descriptor where allocation details will be stored.
    /// @param zSize Size of the memory block to allocate in bytes.
    /// @return JUNO_STATUS_T Status of the allocation operation.
    JUNO_RESULT_POINTER_T (*Get)(JUNO_MEMORY_ALLOC_ROOT_T *ptMem, size_t zSize);

    /// @brief Updates an existing memory allocation to a new size.
    /// 
    /// @param ptMem Pointer to the memory allocation structure.
    /// @param ptMemory Pointer to the memory descriptor to update.
    /// @param zNewSize The new size for the memory block.
    /// @return JUNO_STATUS_T Status of the update operation.
    JUNO_STATUS_T (*Update)(JUNO_MEMORY_ALLOC_ROOT_T *ptMem, JUNO_POINTER_T *ptMemory, size_t zNewSize);

    /// @brief Frees an allocated memory block.
    /// 
    /// @param ptMem Pointer to the memory allocation structure.
    /// @param pvAddr Pointer to the memory block to free.
    /// @return JUNO_STATUS_T Status of the free operation.
    JUNO_STATUS_T (*Put)(JUNO_MEMORY_ALLOC_ROOT_T *ptMem, JUNO_POINTER_T *pvAddr);
};

static inline JUNO_STATUS_T JunoMemory_AllocApiVerify(const JUNO_MEMORY_ALLOC_API_T *ptAllocApi)
{
    JUNO_ASSERT_EXISTS(
        ptAllocApi &&
        ptAllocApi->Get &&
        ptAllocApi->Put &&
        ptAllocApi->Update
    );
    return JUNO_STATUS_SUCCESS;
}

static inline JUNO_STATUS_T JunoMemory_PointerApiVerify(const JUNO_POINTER_API_T *ptPointerApi)
{
    JUNO_ASSERT_EXISTS(
        ptPointerApi &&
        ptPointerApi->Copy &&
        ptPointerApi->Reset
    );
    return JUNO_STATUS_SUCCESS;
}

static inline JUNO_STATUS_T JunoMemory_AllocVerify(const JUNO_MEMORY_ALLOC_ROOT_T *ptAlloc)
{
    JUNO_ASSERT_EXISTS(
        ptAlloc &&
        ptAlloc->ptApi &&
        ptAlloc->ptPointerApi
    );
    JUNO_STATUS_T tStatus = JunoMemory_AllocApiVerify(ptAlloc->ptApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    tStatus = JunoMemory_PointerApiVerify(ptAlloc->ptPointerApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return tStatus;
}

static inline JUNO_STATUS_T JunoMemory_PointerVerify(const JUNO_POINTER_T *ptPointer)
{
    JUNO_ASSERT_EXISTS(
        ptPointer &&
        ptPointer->ptApi &&
        ptPointer->pvAddr &&
        ptPointer->zSize
    );
    JUNO_STATUS_T tStatus = JunoMemory_PointerApiVerify(ptPointer->ptApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return tStatus;
}

#ifdef __cplusplus
}
#endif
#endif // JUNO_MEMORY_API_H
