/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_memory library API
    @author Robin Onsay
*/
#ifndef JUNO_POINTER_API_H
#define JUNO_POINTER_API_H
#include "juno/macros.h"
#include "juno/status.h"
#include "juno/module.h"
#include <stddef.h>
#include <stdalign.h>
#include "juno/types.h"
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_POINTER_TAG JUNO_POINTER_T;
typedef struct JUNO_POINTER_API_TAG JUNO_POINTER_API_T;
typedef struct JUNO_VALUE_POINTER_API_TAG JUNO_VALUE_POINTER_API_T;


/// @brief Structure for an allocated memory segment.
/// Describes the allocated memory with a pointer to the start and its size.
struct JUNO_POINTER_TAG JUNO_TRAIT_ROOT(JUNO_POINTER_API_T,
    /// Pointer to the allocated memory.
    void *pvAddr;
    /// Size of the allocated memory, in bytes.
    size_t zSize;
    /// The memory alignment
    size_t zAlignment;
);

struct JUNO_POINTER_API_TAG
{
    /// Copy memory from one pointer to another
    JUNO_STATUS_T (*Copy)(JUNO_POINTER_T tDest, const JUNO_POINTER_T tSrc);
    /// Reset the memory at the pointer. This could mean zero-initialization
    JUNO_STATUS_T (*Reset)(JUNO_POINTER_T tPointer);
};


struct JUNO_VALUE_POINTER_API_TAG
{
    /// Left == Right
    JUNO_RESULT_BOOL_T (*Equals)(const JUNO_POINTER_T tLeft, const JUNO_POINTER_T tRight);
};

JUNO_MODULE_RESULT(JUNO_RESULT_POINTER_T, JUNO_POINTER_T);
JUNO_MODULE_OPTION(JUNO_OPTION_POINTER_T, JUNO_POINTER_T);

/// Initialize the pointer with an api, type, and address
#define JunoMemory_PointerInit(ptApi, TYPE_T, pvAddr) (JUNO_POINTER_T){ptApi, pvAddr, sizeof(TYPE_T), alignof(TYPE_T)}
/// Initialize a value pointer with an api, type, and address
#define JunoMemory_ValuePointerInit(ptApi, TYPE_T, pvAddr) (JUNO_VALUE_POINTER_T){{{ptApi, pvAddr, sizeof(TYPE_T), alignof(TYPE_T)}}}
/// Verify the pointer and pointer type
#define JunoMemory_PointerVerifyType(pointer, type, tApi) \
(( \
    JunoMemory_PointerVerify(pointer) == JUNO_STATUS_SUCCESS && \
    pointer.ptApi == &tApi && \
    pointer.zSize == sizeof(type) && \
    pointer.zAlignment == alignof(type) && \
    (uintptr_t) pointer.pvAddr % pointer.zAlignment == 0 \
)?JUNO_STATUS_SUCCESS:JUNO_STATUS_ERR)

/// Assert the pointer type
#define JUNO_ASSERT_POINTER_TYPE(tStatus, tPointer, tType, tApi)  JUNO_ASSERT_SUCCESS((tStatus = JunoMemory_PointerVerifyType(tPointer, tType, tApi)), return tStatus)

static inline JUNO_STATUS_T JunoMemory_PointerApiVerify(const JUNO_POINTER_API_T *ptPointerApi)
{
    JUNO_ASSERT_EXISTS(
        ptPointerApi &&
        ptPointerApi->Copy &&
        ptPointerApi->Reset
    );
    return JUNO_STATUS_SUCCESS;
}

static inline JUNO_STATUS_T JunoMemory_ValuePointerApiVerify(const JUNO_VALUE_POINTER_API_T *ptPointerApi)
{
    JUNO_ASSERT_EXISTS(
        ptPointerApi &&
        ptPointerApi->Equals
    );
    return JUNO_STATUS_SUCCESS;
}

static inline JUNO_STATUS_T JunoMemory_PointerVerify(const JUNO_POINTER_T tPointer)
{
    JUNO_ASSERT_EXISTS(
        tPointer.ptApi &&
        tPointer.pvAddr &&
        tPointer.zSize
    );
    JUNO_STATUS_T tStatus = JunoMemory_PointerApiVerify(tPointer.ptApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return tStatus;
}

#ifdef __cplusplus
}
#endif
#endif // JUNO_POINTER_API_H

