/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_memory library API
    @author Robin Onsay
*/
#ifndef JUNO_POINTER_API_H
#define JUNO_POINTER_API_H
#include "juno/macros.h"
#include "juno/status.h"
#include "juno/module.h"
#include <stddef.h>
#include <stdalign.h>
#include "juno/types.h"
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_POINTER_TAG JUNO_POINTER_T;
typedef struct JUNO_POINTER_API_TAG JUNO_POINTER_API_T;
typedef struct JUNO_VALUE_POINTER_API_TAG JUNO_VALUE_POINTER_API_T;
typedef struct JUNO_VALUE_POINTER_TAG JUNO_VALUE_POINTER_T;


/// @brief Structure for an allocated memory segment.
/// Describes the allocated memory with a pointer to the start and its size.
struct JUNO_POINTER_TAG JUNO_TRAIT_ROOT(JUNO_POINTER_API_T,
    /// Pointer to the allocated memory.
    void *pvAddr;
    /// Size of the allocated memory, in bytes.
    size_t zSize;
    size_t zAlignment;
);

struct JUNO_POINTER_API_TAG
{
    /// Copy memory from one pointer to another
    JUNO_STATUS_T (*Copy)(JUNO_POINTER_T tDest, JUNO_POINTER_T tSrc);
    /// Reset the memory at the pointer. This could mean zero-initialization
    JUNO_STATUS_T (*Reset)(JUNO_POINTER_T tPointer);
};

struct JUNO_VALUE_POINTER_TAG JUNO_MODULE_DERIVE_WITH_API(JUNO_POINTER_T, JUNO_VALUE_POINTER_API_T,

);

struct JUNO_VALUE_POINTER_API_TAG JUNO_MODULE_API_DERIVE(JUNO_POINTER_API_T,
    /// Left == Right
    JUNO_RESULT_BOOL_T (*Equals)(JUNO_POINTER_T tLeft, JUNO_POINTER_T tRight);
    /// Left < Right
    JUNO_RESULT_BOOL_T (*Lt)(JUNO_POINTER_T tLeft, JUNO_POINTER_T tRight);
    /// Left <= Right
    JUNO_RESULT_BOOL_T (*Lte)(JUNO_POINTER_T tLeft, JUNO_POINTER_T tRight);
    /// Left > Right
    JUNO_RESULT_BOOL_T (*Gt)(JUNO_POINTER_T tLeft, JUNO_POINTER_T tRight);
    /// Left >= Right
    JUNO_RESULT_BOOL_T (*Gte)(JUNO_POINTER_T tLeft, JUNO_POINTER_T tRight);
);

JUNO_MODULE_RESULT(JUNO_RESULT_POINTER_T, JUNO_POINTER_T);

#define Juno_PointerInit(api, type, addr) (JUNO_POINTER_T){api, addr, sizeof(type), alignof(type)}
#define JUNO_CHECK_POINTER_TYPE(pointer, type) ((pointer.zSize == sizeof(type) && (uintptr_t) pointer.pvAddr % pointer.zAlignment == 0)?JUNO_STATUS_SUCCESS:JUNO_STATUS_ERR)

static inline JUNO_STATUS_T JunoMemory_PointerApiVerify(const JUNO_POINTER_API_T *ptPointerApi)
{
    JUNO_ASSERT_EXISTS(
        ptPointerApi &&
        ptPointerApi->Copy &&
        ptPointerApi->Reset
    );
    return JUNO_STATUS_SUCCESS;
}

static inline JUNO_STATUS_T JunoMemory_ValuePointerApiVerify(const JUNO_VALUE_POINTER_API_T *ptPointerApi)
{
    JUNO_ASSERT_EXISTS(
        ptPointerApi &&
        ptPointerApi->Equals &&
        ptPointerApi->Lt &&
        ptPointerApi->Lte &&
        ptPointerApi->Gt &&
        ptPointerApi->Gte
    );
    return JunoMemory_PointerApiVerify(&ptPointerApi->tRoot);
}

static inline JUNO_STATUS_T JunoMemory_PointerVerify(const JUNO_POINTER_T tPointer)
{
    JUNO_ASSERT_EXISTS(
        tPointer.ptApi &&
        tPointer.pvAddr &&
        tPointer.zSize
    );
    JUNO_STATUS_T tStatus = JunoMemory_PointerApiVerify(tPointer.ptApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return tStatus;
}

#ifdef __cplusplus
}
#endif
#endif // JUNO_POINTER_API_H

