/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_string impl implementation
    @author
*/
#ifndef JUNO_STRING_IMPL_H
#define JUNO_STRING_IMPL_H
#include "juno/module.h"
#include "juno/status.h"
#include "juno/string/string_api.h"
#ifdef __cplusplus
extern "C"
{
#endif


JUNO_MODULE_DERIVE_DECLARE(JUNO_STRING_IMPL_T);

JUNO_MODULE_DERIVE(JUNO_STRING_IMPL_T, JUNO_STRING_ROOT_T,
    /*
    
    TODO: Include implementation specific members here
    
    */
);

#ifdef JUNO_STRING_DEFAULT
/**
    This is the default implementation for `JUNO_STRING_T`.
    If you want to use the default implementation for `JUNO_STRING_T`
    use `#define JUNO_STRING_DEFAULT` prior to including
    `#include "juno_string_impl.h"`

    Note: If you are implementing a derived module you will need
    to implement `JUNO_STRING_IMPL`.
*/
JUNO_MODULE(JUNO_STRING_T, JUNO_STRING_API_T, JUNO_STRING_ROOT_T,
    JUNO_STRING_IMPL_T tJunoStringImpl;
);
#endif

/* TODO: Insert initialization arguments for module members here*/
JUNO_STATUS_T JunoString_ImplApi(JUNO_STRING_T *ptJunoString, JUNO_FAILURE_HANDLER_T pfcnFailureHandler, JUNO_USER_DATA_T *pvFailureUserData);
#ifdef __cplusplus
}
#endif
#endif // JUNO_STRING_IMPL_H

