/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_string library API
    @author
*/
#ifndef JUNO_STRING_API_H
#define JUNO_STRING_API_H
#include "juno/memory/memory_api.h"
#include "juno/status.h"
#include "juno/module.h"
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_STRING_API_TAG JUNO_STRING_API_T;
typedef struct JUNO_STRING_BUFFER_TAG JUNO_STRING_BUFFER_T;

JUNO_MODULE_DECLARE(JUNO_STRING_T);
JUNO_MODULE_ROOT_DECLARE(JUNO_STRING_ROOT_T);


JUNO_MODULE_ROOT(JUNO_STRING_ROOT_T, JUNO_STRING_API_T,
    JUNO_MEMORY_ALLOC_T *ptAlloc;
    JUNO_MEMORY_T tMemory;
    size_t zSize;
);

struct JUNO_STRING_API_TAG
{
    /// Initializes the module and resources for juno_string
    JUNO_STATUS_T (*Init)(JUNO_STRING_T *ptJunoString, JUNO_MEMORY_ALLOC_T *ptAlloc, const char *pcCStr, size_t zCStrSize);
    JUNO_STATUS_T (*Append)(JUNO_STRING_T *ptJunoString, JUNO_STRING_T *ptNewJunoString);
    JUNO_STATUS_T (*AppendCStr)(JUNO_STRING_T *ptJunoString, const char *pcCStr, size_t zCStrSize);
    JUNO_STATUS_T (*GetSize)(JUNO_STRING_T *ptJunoString, size_t *pzSize);
    /// Frees resources allocated by juno_string
    JUNO_STATUS_T (*Free)(JUNO_STRING_T *ptJunoString);
};

#ifdef __cplusplus
}
#endif
#endif // JUNO_STRING_API_H
