/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the template library API
    @author Robin Onsay
*/
#ifndef TEMPLATE_API_H
#define TEMPLATE_API_H
#include "juno/macros.h"
#include "juno/status.h"
#include "juno/module.h"
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct TEMPLATE_API_TAG TEMPLATE_API_T;
typedef struct TEMPLATE_ROOT_TAG TEMPLATE_ROOT_T;

struct TEMPLATE_ROOT_TAG JUNO_MODULE_ROOT(TEMPLATE_API_T,
    /*
    
        TODO: Add implementation independent member variables here
    
    */
);

struct TEMPLATE_API_TAG
{
    /// TODO: Replace this example function with your own functions
    JUNO_STATUS_T (*ExampleFunction)(TEMPLATE_ROOT_T *ptTemplate);
};

static inline JUNO_STATUS_T Template_ApiVerify(const TEMPLATE_API_T *ptTemplateApi)
{
    JUNO_ASSERT_EXISTS(
        ptTemplateApi &&
        ptTemplateApi->ExampleFunction
    );
    return JUNO_STATUS_SUCCESS;
}


static inline JUNO_STATUS_T Template_Verify(TEMPLATE_ROOT_T *ptTemplate)
{
    JUNO_ASSERT_EXISTS(ptTemplate);
    JUNO_STATUS_T tStatus = Template_ApiVerify(ptTemplate->ptApi);
    return tStatus;
}

static inline JUNO_STATUS_T Template_Init(TEMPLATE_ROOT_T *ptTemplate, const TEMPLATE_API_T *ptTemplateApi, JUNO_FAILURE_HANDLER_T pfcnFailureHandler, JUNO_USER_DATA_T *pvFailureUserData)
{
    JUNO_ASSERT_EXISTS(ptTemplate && ptTemplateApi);
    ptTemplate->ptApi = ptTemplateApi;
    ptTemplate->_pfcnFailureHandler = pfcnFailureHandler;
    ptTemplate->_pvFailureUserData = pvFailureUserData;
    return Template_Verify(ptTemplate);
}

#ifdef __cplusplus
}
#endif
#endif // TEMPLATE_API_H
