/**
    @file
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the template impl implementation
    @author
*/
#ifndef TEMPLATE_IMPL_H
#define TEMPLATE_IMPL_H
#include "juno/module.h"
#include "juno/status.h"
#include "template_api.h"
#ifdef __cplusplus
extern "C"
{
#endif


JUNO_MODULE_DERIVE_DECLARE(TEMPLATE_IMPL_T);

JUNO_MODULE_DERIVE(TEMPLATE_IMPL_T, TEMPLATE_BASE_T,
    /*
    
    TODO: Include implementation specific members here
    
    */
);

#define TEMPLATE_IMPL   TEMPLATE_IMPL_T tTemplateImpl

#ifndef TEMPLATE_DERIVED
/**
    This is the default implementation for `TEMPLATE_T`.
    If you want to derive new implementations for `TEMPLATE_T`
    use `#define TEMPLATE_DERIVED` prior to including
    `#include "template_impl.h"`

    Note: If you are implementing a derived module you will need
    to implement `TEMPLATE_IMPL`.
*/
JUNO_MODULE(TEMPLATE_T, TEMPLATE_BASE_T,
    TEMPLATE_IMPL;
);
#endif

/* TODO: Insert initialization arguments for module members here*/
JUNO_STATUS_T Template_ImplApi(TEMPLATE_T *ptTemplate, JUNO_FAILURE_HANDLER_T pfcnFailureHandler, JUNO_USER_DATA_T *pvFailureUserData);
#ifdef __cplusplus
}
#endif
#endif // TEMPLATE_IMPL_H

