#ifndef JUNO_MATH_VEC_H
#define JUNO_MATH_VEC_H

#include "juno/module.h"
#include "juno/types.h"
#include <stddef.h>
#include "juno_math_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/// The linear algebra API
typedef struct JUNO_MATH_LA_API_T JUNO_MATH_LA_API_T;
JUNO_MODULE_DECLARE(JUNO_MATH_VEC_T);

#define JUNO_MATH_CREATE_VEC_TYPE(TYPE_NAME_T, N, type) \
typedef struct TYPE_NAME_T \
{ \
    const size_t iNdim; \
    type tVec[N]; \
} TYPE_NAME_T;

#define JUNO_MATH_CREATE_VEC(TYPE_NAME_T, N) \
JUNO_MATH_CREATE_VEC_TYPE(TYPE_NAME_T##_FLOAT_T, N, float); \
JUNO_MATH_CREATE_VEC_TYPE(TYPE_NAME_T##_DOUBLE_T, N, double); \
JUNO_MATH_CREATE_VEC_TYPE(TYPE_NAME_T##_INT8_T, N, int8_t); \
JUNO_MATH_CREATE_VEC_TYPE(TYPE_NAME_T##_UINT8_T, N, uint8_t); \
JUNO_MATH_CREATE_VEC_TYPE(TYPE_NAME_T##_INT16_T, N, int16_t); \
JUNO_MATH_CREATE_VEC_TYPE(TYPE_NAME_T##_UINT16_T, N, uint16_t); \
JUNO_MATH_CREATE_VEC_TYPE(TYPE_NAME_T##_INT32_T, N, int32_t); \
JUNO_MATH_CREATE_VEC_TYPE(TYPE_NAME_T##_UINT32_T, N, uint32_t); \
JUNO_MATH_CREATE_VEC_TYPE(TYPE_NAME_T##_INT64_T, N, int64_t); \
JUNO_MATH_CREATE_VEC_TYPE(TYPE_NAME_T##_UINT64_T, N, uint64_t); 

#define JUNO_MATH_NEW_VEC_TYPE(tVec, TYPE) ((JUNO_MATH_VEC_##TYPE##_T *)&tVec)
#define JUNO_MATH_NEW_VEC_FLOAT(tVec)   JUNO_MATH_NEW_VEC_TYPE(tVec, FLOAT)
#define JUNO_MATH_NEW_VEC_DOUBLE(tVec)  JUNO_MATH_NEW_VEC_TYPE(tVec, DOUBLE)
#define JUNO_MATH_NEW_VEC_INT8(tVec)    JUNO_MATH_NEW_VEC_TYPE(tVec, INT8)
#define JUNO_MATH_NEW_VEC_UINT8(tVec)   JUNO_MATH_NEW_VEC_TYPE(tVec, UINT8)
#define JUNO_MATH_NEW_VEC_INT16(tVec)   JUNO_MATH_NEW_VEC_TYPE(tVec, INT16)
#define JUNO_MATH_NEW_VEC_UINT16(tVec)  JUNO_MATH_NEW_VEC_TYPE(tVec, UINT16)
#define JUNO_MATH_NEW_VEC_INT32(tVec)   JUNO_MATH_NEW_VEC_TYPE(tVec, INT32)
#define JUNO_MATH_NEW_VEC_UINT32(tVec)  JUNO_MATH_NEW_VEC_TYPE(tVec, UINT32)
#define JUNO_MATH_NEW_VEC_INT64(tVec)   JUNO_MATH_NEW_VEC_TYPE(tVec, INT64)
#define JUNO_MATH_NEW_VEC_UINT64(tVec)  JUNO_MATH_NEW_VEC_TYPE(tVec, UINT64)


JUNO_MATH_CREATE_VEC(JUNO_MATH_VEC, );

#define JUNO_MATH_NEW_VEC2(...)    {2, {__VA_ARGS__}}
JUNO_MATH_CREATE_VEC(JUNO_MATH_VEC2, 2);

#define JUNO_MATH_NEW_VEC3(...)    {3, {__VA_ARGS__}}
JUNO_MATH_CREATE_VEC(JUNO_MATH_VEC3, 3);

#define JUNO_MATH_NEW_VEC4(...)    {4, {__VA_ARGS__}}
JUNO_MATH_CREATE_VEC(JUNO_MATH_VEC4, 4);


#ifdef __cplusplus
}
#endif
#endif
