#ifndef JUNO_TYPES_H
#define JUNO_TYPES_H

#include "juno/module.h"
#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>

#ifndef JUNO_INT_TYPE
#define JUNO_INT_TYPE int64_t
#endif

#ifndef JUNO_FLOAT_TYPE
#define JUNO_FLOAT_TYPE double
#endif

typedef struct JUNO_VEC2_F64_POLAR_TAG
{
    struct{double r, phi;};
} JUNO_VEC2_F64_POLAR_T;

JUNO_MODULE_RESULT(JUNO_VEC2_F64_POLAR_RESULT_T, JUNO_VEC2_F64_POLAR_T);

typedef struct JUNO_VEC2_F64_CART_TAG
{
    struct{double x, y;};
} JUNO_VEC2_F64_CART_T;

JUNO_MODULE_RESULT(JUNO_VEC2_F64_CART_RESULT_T, JUNO_VEC2_F64_CART_T);

typedef union JUNO_VEC2_F64_TAG
{
    JUNO_VEC2_F64_CART_T tCart;
    JUNO_VEC2_F64_POLAR_T tPolar;
    double arr[2];
} JUNO_VEC2_F64_T;

JUNO_MODULE_RESULT(JUNO_VEC2_F64_RESULT_T, JUNO_VEC2_F64_T);

typedef struct JUNO_VEC2_I32_POLAR_TAG
{
    struct{int32_t r, phi;};
} JUNO_VEC2_I32_POLAR_T;

JUNO_MODULE_RESULT(JUNO_VEC2_I32_POLAR_RESULT_T, JUNO_VEC2_I32_POLAR_T);

typedef struct JUNO_VEC2_I32_CART_TAG
{
    struct{int32_t x, y;};
} JUNO_VEC2_I32_CART_T;

JUNO_MODULE_RESULT(JUNO_VEC2_I32_CART_RESULT_T, JUNO_VEC2_I32_CART_T);

typedef union JUNO_VEC2_I32_TAG
{
    JUNO_VEC2_I32_CART_T tCart;
    JUNO_VEC2_I32_POLAR_T tPolar;
    int32_t arr[2];
} JUNO_VEC2_I32_T;

JUNO_MODULE_RESULT(JUNO_VEC2_I32_RESULT_T, JUNO_VEC2_I32_T);

typedef struct JUNO_VEC3_F64_POLAR_TAG
{
    struct{double r, phi, theta;};
} JUNO_VEC3_F64_POLAR_T;

JUNO_MODULE_RESULT(JUNO_VEC3_F64_POLAR_RESULT_T, JUNO_VEC3_F64_POLAR_T);

typedef struct JUNO_VEC3_F64_CART_TAG
{
    struct{double x, y, z;};
} JUNO_VEC3_F64_CART_T;

JUNO_MODULE_RESULT(JUNO_VEC3_F64_CART_RESULT_T, JUNO_VEC3_F64_CART_T);

typedef union JUNO_VEC3_F64_TAG
{
    JUNO_VEC3_F64_CART_T tCart;
    JUNO_VEC3_F64_POLAR_T tPolar;
    double arr[3];
} JUNO_VEC3_F64_T;

JUNO_MODULE_RESULT(JUNO_VEC3F_RESULT_T, JUNO_VEC3_F64_T);

typedef struct JUNO_VEC3_I32_POLAR_TAG
{
    struct{int32_t r, phi, theta;};
} JUNO_VEC3_I32_POLAR_T;

JUNO_MODULE_RESULT(JUNO_VEC3_I32_POLAR_RESULT_T, JUNO_VEC3_I32_POLAR_T);

typedef struct JUNO_VEC3_I32_CART_TAG
{
    struct{int32_t x, y, z;};
} JUNO_VEC3_I32_CART_T;

JUNO_MODULE_RESULT(JUNO_VEC3_I32_CART_RESULT_T, JUNO_VEC3_I32_CART_T);

typedef union JUNO_VEC3_I32_TAG
{
    JUNO_VEC3_I32_CART_T tCart;
    JUNO_VEC3_I32_POLAR_T tPolar;
    int32_t arr[3];
} JUNO_VEC3_I32_T;

JUNO_MODULE_RESULT(JUNO_VEC3_I32_RESULT_T, JUNO_VEC3_I32_T);

typedef struct JUNO_VEC4_F64_POLAR_TAG
{
    struct{double r, phi, theta, rho;};
} JUNO_VEC4_F64_POLAR_T;

JUNO_MODULE_RESULT(JUNO_VEC4_F64_POLAR_RESULT_T, JUNO_VEC4_F64_POLAR_T);

typedef struct JUNO_VEC4_F64_CART_TAG
{
    struct{double x, y, z, w;};
} JUNO_VEC4_F64_CART_T;

JUNO_MODULE_RESULT(JUNO_VEC4_F64_CART_RESULT_T, JUNO_VEC4_F64_CART_T);

typedef union JUNO_VEC4_F64_TAG
{
    JUNO_VEC4_F64_CART_T tCart;
    JUNO_VEC4_F64_POLAR_T tPolar;
    double arr[4];
} JUNO_VEC4_F64_T;

JUNO_MODULE_RESULT(JUNO_VEC4F_RESULT_T, JUNO_VEC3_F64_T);

typedef struct JUNO_VEC4_I32_POLAR_TAG
{
    struct{int32_t r, phi, theta, rho;};
} JUNO_VEC4_I32_POLAR_T;

JUNO_MODULE_RESULT(JUNO_VEC4_I32_POLAR_RESULT_T, JUNO_VEC4_I32_POLAR_T);

typedef struct JUNO_VEC4_I32_CART_TAG
{
    struct{int32_t x, y, z, w;};
} JUNO_VEC4_I32_CART_T;

JUNO_MODULE_RESULT(JUNO_VEC4_I32_CART_RESULT_T, JUNO_VEC4_I32_CART_T);

typedef union JUNO_VEC4_I32_TAG
{
    JUNO_VEC4_I32_CART_T tCart;
    JUNO_VEC4_I32_POLAR_T tPolar;
    int32_t arr[4];
} JUNO_VEC4_I32_T;

JUNO_MODULE_RESULT(JUNO_VEC4_I32_RESULT_T, JUNO_VEC4_I32_T);


typedef struct JUNO_M3X3_F64_TAG
{
    double mat[3][3];
} JUNO_M3X3_F64_T;

JUNO_MODULE_RESULT(JUNO_M3X3F_RESULT_T, JUNO_M3X3_F64_T);

typedef struct JUNO_M4X4_F64_TAG
{
    double mat[4][4];
} JUNO_M4X4_F64_T;

JUNO_MODULE_RESULT(JUNO_M4X4F_RESULT_T, JUNO_M4X4_F64_T);

typedef struct JUNO_M3X3_I32_TAG
{
    int32_t mat[3][3];
} JUNO_M3X3_I32_T;

JUNO_MODULE_RESULT(JUNO_M3X3I_RESULT_T, JUNO_M3X3_I32_T);

typedef struct JUNO_M4X4_I32_TAG
{
    int32_t mat[4][4];
} JUNO_M4X4_I32_T;

JUNO_MODULE_RESULT(JUNO_M4X4I_RESULT_T, JUNO_M4X4_I32_T);

typedef union JUNO_RQUAT_F64_TAG
{
    struct{double s, i, j, k;};
    double quat[4];
} JUNO_RQUAT_F64_T;

JUNO_MODULE_RESULT(JUNO_RQUATF_RESULT_T, JUNO_RQUAT_F64_T);

typedef union JUNO_RQUAT_I32_TAG
{
    struct{int32_t s, i, j, k;};
    int32_t quat[4];
} JUNO_RQUAT_I32_T;

JUNO_MODULE_RESULT(JUNO_RQUATI_RESULT_T, JUNO_RQUAT_I32_T);

#ifdef __cplusplus
}
#endif
#endif