/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the system_manager_app library API
    @author Robin Onsay
*/
#ifndef SYSTEM_MANAGER_APP_API_H
#define SYSTEM_MANAGER_APP_API_H
#include "juno/log/log_api.h"
#include "juno/sb/broker_api.h"
#include "juno/status.h"
#include "juno/module.h"
#include "juno/app/app_api.h"
#include "juno/time/time_api.h"
#include "engine_app/engine_tlm_msg.h"
#include <stdint.h>
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct SYSTEM_MANAGER_APP_API_TAG SYSTEM_MANAGER_APP_API_T;
typedef struct SYSTEM_MANAGER_APP_TAG SYSTEM_MANAGER_APP_T;

#define ENGINE_TLM_MSG_PIPE_DEPTH   (1)

struct SYSTEM_MANAGER_APP_TAG JUNO_MODULE_DERIVE(JUNO_APP_ROOT_T,
    const JUNO_LOG_ROOT_T *ptLogger;
    const JUNO_TIME_ROOT_T *ptTime;
    JUNO_SB_BROKER_ROOT_T *ptBroker;
    ENGINE_TLM_MSG_T ptArrEngineTlmBuff[ENGINE_TLM_MSG_PIPE_DEPTH];
    ENGINE_TLM_MSG_ARRAY_T tEngineTlmArray;
    JUNO_SB_PIPE_T tEngineTlmPipe;
    JUNO_TIMESTAMP_T tEngineStart;
    float fTargetRpm;
);

JUNO_STATUS_T SystemManagerApp(
    SYSTEM_MANAGER_APP_T *ptSystemManagerApp,
    JUNO_LOG_ROOT_T *ptLogger,
    JUNO_TIME_ROOT_T *ptTime,
    JUNO_SB_BROKER_ROOT_T *ptBroker,
    JUNO_FAILURE_HANDLER_T pfcnFailureHandler,
    JUNO_USER_DATA_T *pvUserData
);

#ifdef __cplusplus
}
#endif
#endif // SYSTEM_MANAGER_APP_API_H
