/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the template_app library API
    @author
*/
#ifndef TEMPLATE_APP_API_H
#define TEMPLATE_APP_API_H
#include "juno/log/log_api.h"
#include "juno/status.h"
#include "juno/module.h"
#include "juno/app/app_api.h"
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct TEMPLATE_APP_API_TAG TEMPLATE_APP_API_T;
JUNO_MODULE_DERIVE_DECLARE(TEMPLATE_APP_T);

JUNO_MODULE_DERIVE(TEMPLATE_APP_T, JUNO_APP_BASE_T,
    JUNO_LOG_T *ptLogger;
);

JUNO_STATUS_T TemplateApp(
    JUNO_APP_T *ptTemplateApp,
    JUNO_LOG_T *ptLogger,
    JUNO_FAILURE_HANDLER_T pfcnFailureHandler,
    JUNO_USER_DATA_T *pvUserData
);

#ifdef __cplusplus
}
#endif
#endif // TEMPLATE_APP_API_H
