/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_sm impl implementation
    @author Robin Onsay
*/
#ifndef JUNO_SM_IMPL_H
#define JUNO_SM_IMPL_H
#include "juno/module.h"
#include "juno/status.h"
#include "sm_api.h"
#ifdef __cplusplus
extern "C"
{
#endif


typedef struct JUNO_SM_IMPL_TAG JUNO_SM_IMPL_T;

struct JUNO_SM_IMPL_TAG JUNO_MODULE_DERIVE(JUNO_SM_ROOT_T,
    /*
    
    TODO: Include implementation specific members here
    
    */
);

#ifndef JUNO_SM_CUSTOM
/**
    This is the default implementation for `JUNO_SM_T`.
    If you want to use the default implementation for `JUNO_SM_T`
    use `#define JUNO_SM_DEFAULT` prior to including
    `#include "juno_sm_impl.h"`

    Note: If you are implementing a derived module you will need
    to implement `JUNO_SM_IMPL`.
*/
union JUNO_SM_TAG JUNO_MODULE(JUNO_SM_API_T, JUNO_SM_ROOT_T,
    JUNO_SM_IMPL_T tJunoSmImpl;
);
#endif

/* TODO: Insert initialization arguments for module members here*/
JUNO_STATUS_T JunoSm_ImplApi(JUNO_SM_T *ptJunoSm, JUNO_FAILURE_HANDLER_T pfcnFailureHandler, JUNO_USER_DATA_T *pvFailureUserData);
#ifdef __cplusplus
}
#endif
#endif // JUNO_SM_IMPL_H

