/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_sm library API
    @author Robin Onsay
*/
#ifndef JUNO_SM_API_H
#define JUNO_SM_API_H
#include "juno/status.h"
#include "juno/module.h"
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_SM_STATE_API_TAG JUNO_SM_STATE_API_T;

typedef union JUNO_SM_STATE_T JUNO_SM_STATE_T;
typedef struct JUNO_SM_STATE_ROOT_TAG JUNO_SM_STATE_ROOT_T;

struct JUNO_SM_ROOT_TAG JUNO_MODULE_ROOT(JUNO_SM_STATE_API_T,
    /*
    
        TODO: Add implementation independent member variables here
    
    */
);

struct JUNO_SM_API_TAG
{
    JUNO_STATUS_T (*ShouldExit)(JUNO_SM_STATE_T *ptJunoSm);
    JUNO_STATUS_T (*StateAction)(JUNO_SM_STATE_T *ptJunoSm);
};

#ifdef __cplusplus
}
#endif
#endif // JUNO_SM_API_H
