/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_sm library API
    @author Robin Onsay
*/
#ifndef JUNO_SM_API_H
#define JUNO_SM_API_H
#include "juno/macros.h"
#include "juno/status.h"
#include "juno/module.h"
#include "juno/types.h"
#include <stddef.h>
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_SM_ROOT_TAG JUNO_SM_ROOT_T;
typedef struct JUNO_SM_STATE_API_TAG JUNO_SM_STATE_API_T;

JUNO_MODULE_DECLARE(JUNO_SM_STATE_T);
JUNO_MODULE_DECLARE(JUNO_SM_T);
typedef struct JUNO_SM_STATE_ROOT_TAG JUNO_SM_STATE_ROOT_T;

/// A result type for returning a SM state
JUNO_MODULE_RESULT(JUNO_SM_RESULT_STATE_T, JUNO_SM_STATE_T *);
JUNO_MODULE_OPTION(JUNO_SM_OPTION_STATE_T, JUNO_SM_STATE_T *);
JUNO_MODULE_RESULT(JUNO_SM_RESULT_OPTION_STATE_T, JUNO_SM_OPTION_STATE_T);

/// A State Machine State
struct JUNO_SM_STATE_ROOT_TAG JUNO_MODULE_ROOT(JUNO_SM_STATE_API_T,
    JUNO_SM_T *ptSm;
    JUNO_SM_STATE_T *ptNextState;
);

struct JUNO_SM_STATE_API_TAG
{
    /// The action that should be executed in this state
    JUNO_STATUS_T (*StateAction)(JUNO_SM_STATE_T *ptJunoSm);
    /// Returns a bool result whether the current state should exit
    JUNO_RESULT_BOOL_T (*ShouldExit)(JUNO_SM_STATE_T *ptJunoSm);
    /// Reset the state
    JUNO_STATUS_T (*ResetState)(JUNO_SM_STATE_T *ptJunoSm);
};

struct JUNO_SM_ROOT_TAG JUNO_MODULE_ROOT(void,
    /// The current state
    JUNO_SM_STATE_T *ptCurrentState;
);

/// Verify if this is a valid state machine
static inline JUNO_STATUS_T JunoSm_Verify(JUNO_SM_T *ptSm)
{
    JUNO_ASSERT_EXISTS(ptSm);
    JUNO_SM_ROOT_T *ptSmRoot = (JUNO_SM_ROOT_T *) ptSm;
    JUNO_ASSERT_EXISTS(ptSmRoot->ptCurrentState);
    return JUNO_STATUS_SUCCESS;
}

static inline JUNO_STATUS_T JunoSm_StateVerify(JUNO_SM_STATE_T *ptSmState)
{
    JUNO_ASSERT_EXISTS(ptSmState);
    JUNO_SM_STATE_ROOT_T *ptSmRoot = (JUNO_SM_STATE_ROOT_T *) ptSmState;
    JUNO_ASSERT_EXISTS(ptSmRoot->ptApi && ptSmRoot->ptSm);
    return JUNO_STATUS_SUCCESS;
}

static inline JUNO_STATUS_T JunoSm_StateInit(JUNO_SM_T *ptSm, JUNO_SM_STATE_T *ptState, JUNO_SM_STATE_T *ptNextState, const JUNO_SM_STATE_API_T *ptStateApi, JUNO_FAILURE_HANDLER_T pfcnFailureHandler, JUNO_USER_DATA_T *pvFailureUserData)
{
    JUNO_ASSERT_EXISTS(ptState && ptStateApi && ptSm);
    JUNO_SM_STATE_ROOT_T *ptStateRoot = (JUNO_SM_STATE_ROOT_T *) (ptState);
    ptStateRoot->ptSm = ptSm;
    ptStateRoot->_pfcnFailureHandler = pfcnFailureHandler;
    ptStateRoot->_pvFailureUserData = pvFailureUserData;
    ptStateRoot->ptApi = ptStateApi;
    ptStateRoot->ptNextState = ptNextState;
    return JunoSm_StateVerify(ptState);
}

static inline JUNO_STATUS_T JunoSm_Init(JUNO_SM_T *ptSm, JUNO_SM_STATE_T *ptStartState, JUNO_FAILURE_HANDLER_T pfcnFailureHandler, JUNO_USER_DATA_T *pvFailureUserData)
{
    JUNO_ASSERT_EXISTS(ptSm);
    JUNO_SM_ROOT_T *ptSmRoot = (JUNO_SM_ROOT_T *) ptSm;
    ptSmRoot->ptCurrentState = ptStartState;
    ptSmRoot->_pfcnFailureHandler = pfcnFailureHandler;
    ptSmRoot->_pvFailureUserData = pvFailureUserData;
    JUNO_STATUS_T tStatus = JunoSm_Verify(ptSm);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return tStatus;
}

static inline JUNO_SM_RESULT_STATE_T JunoSm_GetCurrentState(JUNO_SM_T *ptSm)
{
    JUNO_SM_RESULT_STATE_T tResult = {JUNO_STATUS_ERR, NULL};
    tResult.tStatus = JunoSm_Verify(ptSm);
    JUNO_ASSERT_SUCCESS(tResult.tStatus, return tResult);
    JUNO_SM_ROOT_T *ptSmRoot = (JUNO_SM_ROOT_T *) ptSm;
    tResult.tStatus = JUNO_STATUS_SUCCESS;
    tResult.tOk = ptSmRoot->ptCurrentState;
    return tResult;
}

static inline JUNO_SM_RESULT_STATE_T JunoSm_TransitionState(JUNO_SM_T *ptSm)
{
    JUNO_SM_RESULT_STATE_T tResult = {JUNO_STATUS_ERR, NULL};
    tResult.tStatus = JunoSm_Verify(ptSm);
    JUNO_ASSERT_SUCCESS(tResult.tStatus, return tResult);
    JUNO_SM_ROOT_T *ptSmRoot = (JUNO_SM_ROOT_T *) ptSm;
    tResult.tStatus = JUNO_STATUS_SUCCESS;
    JUNO_SM_STATE_ROOT_T *ptCurrentStateRoot = (JUNO_SM_STATE_ROOT_T*) ptSmRoot->ptCurrentState;
    ptSmRoot->ptCurrentState = ptCurrentStateRoot->ptNextState;
    tResult.tOk = ptSmRoot->ptCurrentState;
    return tResult;
}

#ifdef __cplusplus
}
#endif
#endif // JUNO_SM_API_H
