/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_app library API
    @author
*/
#ifndef JUNO_APP_API_H
#define JUNO_APP_API_H
#include "juno/status.h"
#include "juno/module.h"
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_APP_API_TAG JUNO_APP_API_T;

typedef union JUNO_APP_T JUNO_APP_T;
typedef struct JUNO_APP_ROOT_TAG JUNO_APP_ROOT_T;

struct JUNO_APP_ROOT_TAG JUNO_MODULE_ROOT(JUNO_APP_API_T, JUNO_MODULE_EMPTY);

struct JUNO_APP_API_TAG
{
    JUNO_STATUS_T (*OnInit)(JUNO_APP_T *ptJunoApp);
    JUNO_STATUS_T (*OnProcess)(JUNO_APP_T *ptJunoApp);
    JUNO_STATUS_T (*OnExit)(JUNO_APP_T *ptJunoApp);
};

#ifdef __cplusplus
}
#endif
#endif // JUNO_APP_API_H
