/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
 * @file hash_djb2.h
 * @brief djb2 hash implementation (unsigned size_t variant).
 * @defgroup juno_hash Hash Utilities
 * @details
 *  Computes the classic djb2 hash over a byte buffer using the recurrence
 *  h = h * 33 + x. The initial value is 5381. Returns the result as size_t.
 */
#ifndef JUNO_HASH_DJB2_H
#define JUNO_HASH_DJB2_H
#include "juno/status.h"
#include "juno/types.h"
#ifdef __cplusplus
extern "C"
{
#endif


/**
 * @brief Compute djb2 hash over a byte buffer.
 * @param pcBuff Pointer to input bytes (must not be NULL unless zBuffSize==0).
 * @param zBuffSize Number of bytes to hash.
 * @return Result containing the hash value or an error for invalid input.
 */
static inline JUNO_RESULT_SIZE_T JunoHash_Djb2(const uint8_t *pcBuff, size_t zBuffSize)
{
    JUNO_RESULT_SIZE_T tResult = {0, 0};
    if(!(pcBuff))
    {
        tResult.tStatus = JUNO_STATUS_NULLPTR_ERROR;
        return tResult;
    }
    size_t zHash = 5381;
    for(size_t i = 0; i < zBuffSize; i++)
    {
        zHash = ((zHash << 5) + zHash) + pcBuff[i];
    }
    tResult.tStatus = JUNO_STATUS_SUCCESS;
    tResult.tOk = zHash;
    return tResult;
}
#ifdef __cplusplus
}
#endif
#endif // JUNO_HASH_DJB2_H

