/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_hash library API
    @author
*/
#ifndef JUNO_HASH_API_H
#define JUNO_HASH_API_H
#include "juno/status.h"
#include "juno/module.h"
#include <stddef.h>
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_HASH_API_TAG JUNO_HASH_API_T;

JUNO_MODULE_DECLARE(JUNO_HASH_T);
JUNO_MODULE_ROOT_DECLARE(JUNO_HASH_ROOT_T);

JUNO_MODULE_ROOT(JUNO_HASH_ROOT_T, JUNO_HASH_API_T, JUNO_MODULE_EMPTY);

struct JUNO_HASH_API_TAG
{

    JUNO_STATUS_T (*Hash)(JUNO_HASH_T *ptHash, const uint8_t *pcBuff, size_t zBuffSize, size_t *pzRetHash);

};

#ifdef __cplusplus
}
#endif
#endif // JUNO_HASH_API_H
