/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_hash djb2 implementation
    @author Robin Onsay
*/
#ifndef JUNO_HASH_DJB2_H
#define JUNO_HASH_DJB2_H
#include "juno/status.h"
#include "juno/types.h"
#ifdef __cplusplus
extern "C"
{
#endif


static inline JUNO_RESULT_SIZE_T JunoHash_Djb2(const uint8_t *pcBuff, size_t zBuffSize)
{
    JUNO_RESULT_SIZE_T tResult = {0, 0};
    if(!(pcBuff))
    {
        tResult.tStatus = JUNO_STATUS_NULLPTR_ERROR;
        return tResult;
    }
    size_t zHash = 5381;
    for(size_t i = 0; i < zBuffSize; i++)
    {
        zHash = ((zHash << 5) + zHash) + pcBuff[i];
    }
    tResult.tStatus = JUNO_STATUS_SUCCESS;
    tResult.tOk = zHash;
    return tResult;
}
#ifdef __cplusplus
}
#endif
#endif // JUNO_HASH_DJB2_H

