/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_hash djb2 djb2ementation
    @author
*/
#ifndef JUNO_HASH_DJB2_H
#define JUNO_HASH_DJB2_H
#include "juno/module.h"
#include "juno/status.h"
#include "juno/hash/hash_api.h"
#ifdef __cplusplus
extern "C"
{
#endif


typedef struct JUNO_HASH_DJB2_TAG JUNO_HASH_DJB2_T;

struct JUNO_HASH_DJB2_TAG JUNO_MODULE_DERIVE(JUNO_HASH_ROOT_T, JUNO_MODULE_EMPTY);

#ifdef JUNO_HASH_DEFAULT
/**
    This is the default djb2ementation for `JUNO_HASH_T`.
    If you want to use the default djb2ementation for `JUNO_HASH_T`
    use `#define JUNO_HASH_DEFAULT` prior to including
    `#include "juno_hash_djb2.h"`

    Note: If you are djb2ementing a derived module you will need
    to djb2ement `JUNO_HASH_DJB2`.
*/
union JUNO_HASH_TAG JUNO_MODULE(JUNO_HASH_API_T, JUNO_HASH_ROOT_T,
    JUNO_HASH_DJB2_T tJunoHashDjb2;
);
#endif

/* TODO: Insert initialization arguments for module members here*/
JUNO_STATUS_T JunoHash_Djb2Api(JUNO_HASH_T *ptJunoHash, JUNO_FAILURE_HANDLER_T pfcnFailureHandler, JUNO_USER_DATA_T *pvFailureUserData);
#ifdef __cplusplus
}
#endif
#endif // JUNO_HASH_DJB2_H

