/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
 * @file mtx_api.h
 * @brief Minimal mutex API for cooperative concurrency.
 * @defgroup juno_mp_mtx Mutex API
 * @details
 *  A small abstraction over a mutual exclusion primitive. Implementations
 *  may busy-wait in Lock; TryLock is non-blocking and returns a bool result.
 */
#ifndef JUNO_MP_MTX_API_H
#define JUNO_MP_MTX_API_H
#include "juno/macros.h"
#ifdef __cplusplus
extern "C"
{
#endif
#include "juno/status.h"
#include "juno/module.h"
#include "juno/types.h"
typedef struct JUNO_MP_MTX_ROOT_TAG JUNO_MP_MTX_ROOT_T;
typedef struct JUNO_MP_MTX_API_TAG JUNO_MP_MTX_API_T;

struct JUNO_MP_MTX_ROOT_TAG JUNO_MODULE_ROOT(JUNO_MP_MTX_API_T, JUNO_MODULE_EMPTY);

struct JUNO_MP_MTX_API_TAG
{
    /// @brief Attempt to acquire the lock and return immediately.
    JUNO_RESULT_BOOL_T (*TryLock)(JUNO_MP_MTX_ROOT_T *ptMtx);
    /// @brief Busy-wait until the lock is acquired.
    JUNO_STATUS_T (*Lock)(JUNO_MP_MTX_ROOT_T *ptMtx);
    /// @brief Release the lock.
    JUNO_STATUS_T (*Free)(JUNO_MP_MTX_ROOT_T *ptMtx);
};

/// @brief Verify a mutex instance and its API table.
static inline JUNO_STATUS_T JunoMp_MtxVerify(const JUNO_MP_MTX_ROOT_T *ptMtx)
{
    JUNO_ASSERT_EXISTS(
        ptMtx &&
        ptMtx->ptApi &&
        ptMtx->ptApi->TryLock &&
        ptMtx->ptApi->Lock &&
        ptMtx->ptApi->Free
    );
    return JUNO_STATUS_SUCCESS;
}

#ifdef __cplusplus
}
#endif
#endif // JUNO_MP_MTX_API_H
