/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_buff_queue library API
    @author
*/
#ifndef JUNO_BUFF_QUEUE_API_H
#define JUNO_BUFF_QUEUE_API_H
#include "juno/macros.h"
#include "juno/memory/memory_api.h"
#include "juno/status.h"
#include "juno/module.h"
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_BUFF_QUEUE_API_TAG JUNO_BUFF_QUEUE_API_T;
typedef struct JUNO_BUFF_QUEUE_TAG JUNO_BUFF_QUEUE_T;


struct JUNO_BUFF_QUEUE_TAG
{
    size_t iStartIndex;
    size_t zLength;
    size_t zCapacity;
    JUNO_FAILURE_HANDLER_T JUNO_FAILURE_HANDLER;
    JUNO_USER_DATA_T *JUNO_FAILURE_USER_DATA;
};

static inline JUNO_STATUS_T JunoBuff_QueueInit(JUNO_BUFF_QUEUE_T *ptQueue, size_t zCapacity, JUNO_FAILURE_HANDLER_T pfcnFailureHdlr, JUNO_USER_DATA_T *pvFailureUserData)
{
    ASSERT_EXISTS(ptQueue);
    ptQueue->iStartIndex = 0;
    ptQueue->zLength = 0;
    ptQueue->zCapacity = zCapacity;
    ptQueue->_pfcnFailureHandler = pfcnFailureHdlr;
    ptQueue->_pvFailurUserData = pvFailureUserData;
    return JUNO_STATUS_SUCCESS;
}

static inline JUNO_STATUS_T JunoBuff_QueueEnqueue(JUNO_BUFF_QUEUE_T *ptQueue, size_t *ptRetIndex)
{
    ASSERT_EXISTS(ptQueue);
    if(ptQueue->zLength < ptQueue->zCapacity)
    {
        ptQueue->zLength += 1;
    }
    else
    {
        FAIL(JUNO_STATUS_INVALID_SIZE_ERROR, ptQueue->_pfcnFailureHandler, ptQueue->_pvFailurUserData, "Failed to enqueue data");
        return JUNO_STATUS_INVALID_SIZE_ERROR;
    }
    if(ptRetIndex)
    {
        *ptRetIndex = ptQueue->zLength % ptQueue->zCapacity;
    }
    return JUNO_STATUS_SUCCESS;
}

static inline JUNO_STATUS_T JunoBuff_QueueDequeue(JUNO_BUFF_QUEUE_T *ptQueue, size_t *ptRetIndex)
{
    ASSERT_EXISTS(ptQueue);
    if(ptQueue->zLength > 0)
    {
        ptQueue->iStartIndex = (ptQueue->iStartIndex + 1) % ptQueue->zCapacity;
        ptQueue->zLength -= 1;
        if(ptRetIndex)
        {
            *ptRetIndex = ptQueue->iStartIndex;
        }
        return JUNO_STATUS_SUCCESS;
    }
    FAIL(JUNO_STATUS_ERR, ptQueue->_pfcnFailureHandler, ptQueue->_pvFailurUserData, "Queue is empty");
    return JUNO_STATUS_ERR;
}

static inline JUNO_STATUS_T JunoBuff_QueueGetIndex(JUNO_BUFF_QUEUE_T *ptQueue, size_t *ptRetIndex)
{
    ASSERT_EXISTS(ptQueue);
    if(*ptRetIndex)
    {
        *ptRetIndex = ptQueue->iStartIndex;
    }
    return JUNO_STATUS_SUCCESS;
}


#ifdef __cplusplus
}
#endif
#endif // JUNO_BUFF_QUEUE_API_H
