/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_buff_queue library API
    @author
*/
#ifndef JUNO_BUFF_QUEUE_API_HPP
#define JUNO_BUFF_QUEUE_API_HPP
#include "juno/status.h"
#include "juno/module.h"
#include "juno/module.hpp"
#include "juno/types.hpp"
#include <cstddef>

namespace juno
{
namespace buff
{

template<typename T, const size_t N>
struct QUEUE_API_T;

template<typename T, const size_t N>
union QUEUE_T;

template<typename T, const size_t N>
struct QUEUE_ROOT_T JUNO_MODULE_ROOT(JUNO_MODULE_ARG(QUEUE_API_T<T,N>),
    ARRAY_T<T,N> *ptArrBuff;
    size_t iStartIndex;
    size_t zLength;
);

template<typename T, const size_t N>
struct QUEUE_API_T
{
    JUNO_STATUS_T (*Enqueue)(QUEUE_T<T, N>& tQueue, T tData);
    RESULT_T<T> (*Dequeue)(QUEUE_T<T, N>& tQueue);
    RESULT_T<T*> (*Peek)(QUEUE_T<T, N>& tQueue);
};



template<typename T, const size_t N>
struct STACK_API_T;

template<typename T, const size_t N>
union STACK_T;

template<typename T, const size_t N>
struct STACK_ROOT_T JUNO_MODULE_ROOT(JUNO_MODULE_ARG(STACK_API_T<T,N>),
    ARRAY_T<T,N> *ptArrBuff;
    size_t zLength;
);

template<typename T, const size_t N>
struct STACK_API_T
{
    JUNO_STATUS_T (*Push)(STACK_T<T, N>& tStack, T tData);
    RESULT_T<T> (*Pop)(STACK_T<T, N>& tStack);
    RESULT_T<T*> (*Peek)(STACK_T<T, N>& tStack);
};

}
}

#endif // JUNO_BUFF_QUEUE_API_H
