/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_buff_queue library API
    @author
*/
#ifndef JUNO_BUFF_QUEUE_API_H
#define JUNO_BUFF_QUEUE_API_H
#include "juno/macros.h"
#include "juno/memory/memory_api.h"
#include "juno/status.h"
#include "juno/module.h"
#include "juno/types.h"
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_BUFF_QUEUE_API_TAG JUNO_BUFF_QUEUE_API_T;
typedef struct JUNO_BUFF_QUEUE_TAG JUNO_BUFF_QUEUE_ROOT_T;


struct JUNO_BUFF_QUEUE_TAG JUNO_MODULE_ROOT(JUNO_BUFF_QUEUE_ROOT_T,
    size_t iStartIndex;
    size_t zLength;
    size_t zCapacity;
);

static inline JUNO_STATUS_T JunoBuff_QueueInit(JUNO_BUFF_QUEUE_ROOT_T *ptQueue, size_t zCapacity, JUNO_FAILURE_HANDLER_T pfcnFailureHdlr, JUNO_USER_DATA_T *pvFailureUserData)
{
    ASSERT_EXISTS(ptQueue);
    ptQueue->iStartIndex = 0;
    ptQueue->zLength = 0;
    ptQueue->zCapacity = zCapacity;
    ptQueue->_pfcnFailureHandler = pfcnFailureHdlr;
    ptQueue->_pvFailurUserData = pvFailureUserData;
    return JUNO_STATUS_SUCCESS;
}

static inline JUNO_RESULT_SIZE_T JunoBuff_QueueEnqueue(JUNO_BUFF_QUEUE_ROOT_T *ptQueue)
{
    JUNO_RESULT_SIZE_T tResult = {JUNO_STATUS_SUCCESS,0};
    if(!ptQueue)
    {
        tResult.tStatus = JUNO_STATUS_NULLPTR_ERROR;
        return tResult;
    }
    if(ptQueue->zLength < ptQueue->zCapacity)
    {
        tResult.tSuccess = (ptQueue->iStartIndex + ptQueue->zLength) % ptQueue->zCapacity;
        ptQueue->zLength += 1;
    }
    else
    {
        tResult.tStatus = JUNO_STATUS_INVALID_SIZE_ERROR;
        JUNO_FAIL(tResult.tStatus, ptQueue->_pfcnFailureHandler, ptQueue->_pvFailurUserData, "Failed to enqueue data");
        return tResult;
    }
    return tResult;
}

static inline JUNO_RESULT_SIZE_T JunoBuff_QueueDequeue(JUNO_BUFF_QUEUE_ROOT_T *ptQueue)
{
    JUNO_RESULT_SIZE_T tResult = {JUNO_STATUS_SUCCESS,0};
    if(!ptQueue)
    {
        tResult.tStatus = JUNO_STATUS_NULLPTR_ERROR;
        return tResult;
    }
    if(ptQueue->zLength > 0)
    {
        tResult.tSuccess = ptQueue->iStartIndex;
        ptQueue->iStartIndex = (ptQueue->iStartIndex + 1) % ptQueue->zCapacity;
        ptQueue->zLength -= 1;
        return tResult;
    }
    tResult.tStatus = JUNO_STATUS_ERR;
    JUNO_FAIL(tResult.tStatus, ptQueue->_pfcnFailureHandler, ptQueue->_pvFailurUserData, "Queue is empty");
    return tResult;
}

static inline JUNO_RESULT_SIZE_T JunoBuff_QueueGetIndex(JUNO_BUFF_QUEUE_ROOT_T *ptQueue)
{
    JUNO_RESULT_SIZE_T tResult = {JUNO_STATUS_SUCCESS,0};
    if(!ptQueue)
    {
        tResult.tStatus = JUNO_STATUS_NULLPTR_ERROR;
        return tResult;
    }
    tResult.tSuccess = ptQueue->iStartIndex;
    return tResult;
}


#ifdef __cplusplus
}
#endif
#endif // JUNO_BUFF_QUEUE_API_H
