/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_buff_queue library API
    @author
*/
#ifndef JUNO_BUFF_HPP
#define JUNO_BUFF_HPP
#include "buff_api.hpp"
#include "juno/buff/buff_queue_api.h"
#include "juno/buff/buff_stack_api.h"
#include "juno/module.h"
#include "juno/module.hpp"
#include "juno/status.h"

namespace juno
{
namespace buff
{
template<typename T, const size_t N>
JUNO_STATUS_T Enqueue(QUEUE_T<T, N>& tQueue, T tData);
template<typename T, const size_t N>
RESULT_T<T> Dequeue(QUEUE_T<T, N>& tQueue);
template<typename T, const size_t N>
RESULT_T<T*> QueuePeek(QUEUE_T<T, N>& tQueue);

template<typename T, const size_t N>
struct JUNO_QUEUE_T JUNO_MODULE_DERIVE(JUNO_BUFF_QUEUE_ROOT_T,
    ARRAY_T<T,N> *ptArrBuff;

    static RESULT_T<JUNO_QUEUE_T<T, N>> New(const QUEUE_API_T<T,N> *ptApi, ARRAY_T<T,N>& tArr, JUNO_FAILURE_HANDLER_T pfcnFailureHandler, JUNO_USER_DATA_T *pvFailureUserData)
    {
        JUNO_QUEUE_T<T, N>tNew{};
        tNew.ptArrBuff = &tArr;
        tNew.tRoot.ptApi = ptApi;
        tNew.tRoot._pfcnFailureHandler = pfcnFailureHandler;
        tNew.tRoot._pvFailureUserData = pvFailureUserData;
        tNew.tRoot.iStartIndex = 0;
        tNew.tRoot.zLength = 0;
        return RESULT_T<JUNO_QUEUE_T<T, N>>{JUNO_STATUS_SUCCESS, tNew};
    }
    static constexpr QUEUE_API_T<T, N> NewApi()
    {
        return {Enqueue<T,N>, Dequeue<T,N>, QueuePeek<T,N>};
    }
);

#ifndef JUNO_QUEUE_CUSTOM

template<typename T, const size_t N>
union QUEUE_T JUNO_MODULE(JUNO_MODULE_ARG(QUEUE_API_T<T, N>), JUNO_BUFF_QUEUE_ROOT_T,
    JUNO_QUEUE_T<T,N> tJunoQueue;
);

#endif

template<typename T, const size_t N>
RESULT_T<T> Dequeue(QUEUE_T<T, N>& tQueue)
{
    auto& tJunoQueue = reinterpret_cast<JUNO_QUEUE_T<T, N>&>(tQueue);
    RESULT_T<T> tResult{JUNO_STATUS_SUCCESS, {}};
    if(tJunoQueue.tRoot.zLength > 0)
    {
        tResult.tSuccess = tJunoQueue.ptArrBuff->tArr[tJunoQueue.tRoot.iStartIndex];
        tJunoQueue.tRoot.iStartIndex = (tJunoQueue.tRoot.iStartIndex + 1) % N;
        tJunoQueue.tRoot.zLength -= 1;
        return tResult;
    }
    tResult.tStatus = JUNO_STATUS_ERR;
    JUNO_FAIL(tResult.tStatus, tJunoQueue.tRoot._pfcnFailureHandler, tJunoQueue.tRoot._pvFailureUserData, "Queue is empty");
    return tResult;
}

template<typename T, const size_t N>
JUNO_STATUS_T Enqueue(QUEUE_T<T, N>& tQueue, T tData)
{
    auto& tJunoQueue = reinterpret_cast<JUNO_QUEUE_T<T, N>&>(tQueue);
    if(tJunoQueue.tRoot.zLength < N)
    {
        tJunoQueue.ptArrBuff->tArr[(tJunoQueue.tRoot.iStartIndex + tJunoQueue.tRoot.zLength) % N] = tData;
        tJunoQueue.tRoot.zLength += 1;
        return JUNO_STATUS_SUCCESS;
    }
    JUNO_FAIL(JUNO_STATUS_INVALID_SIZE_ERROR, tJunoQueue.tRoot._pfcnFailureHandler, tJunoQueue.tRoot._pvFailureUserData, "Queue is full");
    return JUNO_STATUS_INVALID_SIZE_ERROR;
}

template<typename T, const size_t N>
RESULT_T<T*> QueuePeek(QUEUE_T<T, N>& tQueue)
{
    auto& tJunoQueue = reinterpret_cast<JUNO_QUEUE_T<T, N>&>(tQueue);
    RESULT_T<T*> tResult{JUNO_STATUS_SUCCESS, {}};
    if(tJunoQueue.tRoot.zLength > 0)
    {
        tResult.tSuccess = &tJunoQueue.ptArrBuff->tArr[tJunoQueue.tRoot.iStartIndex];
        return tResult;
    }
    tResult.tStatus = JUNO_STATUS_ERR;
    JUNO_FAIL(tResult.tStatus, tJunoQueue.tRoot._pfcnFailureHandler, tJunoQueue.tRoot._pvFailureUserData, "Queue is empty");
    return tResult;
}

template<typename T, const size_t N>
JUNO_STATUS_T Push(STACK_T<T, N>& tStack, T tData);
template<typename T, const size_t N>
RESULT_T<T> Pop(STACK_T<T, N>& tStack);
template<typename T, const size_t N>
RESULT_T<T*> StackPeek(STACK_T<T, N>& tStack);

template<typename T, const size_t N>
struct JUNO_STACK_T JUNO_MODULE_DERIVE(JUNO_BUFF_STACK_ROOT_T,
    ARRAY_T<T,N> *ptArrBuff;

    static RESULT_T<JUNO_STACK_T<T, N>> New(const STACK_API_T<T,N> *ptApi, ARRAY_T<T,N>& tArr, JUNO_FAILURE_HANDLER_T pfcnFailureHandler, JUNO_USER_DATA_T *pvFailureUserData)
    {
        JUNO_STACK_T<T, N>tNew{};
        tNew.ptArrBuff = &tArr;
        tNew.tRoot.ptApi = ptApi;
        tNew.tRoot._pfcnFailureHandler = pfcnFailureHandler;
        tNew.tRoot._pvFailureUserData = pvFailureUserData;
        tNew.tRoot.zLength = 0;
        return RESULT_T<JUNO_STACK_T<T, N>>{JUNO_STATUS_SUCCESS, tNew};
    }

    static constexpr STACK_API_T<T, N> NewApi()
    {
        return {Push<T,N>, Pop<T,N>, StackPeek<T,N>};
    }

);

#ifndef JUNO_STACK_CUSTOM

template<typename T, const size_t N>
union STACK_T JUNO_MODULE(JUNO_MODULE_ARG(STACK_API_T<T, N>), JUNO_BUFF_STACK_ROOT_T,
    JUNO_STACK_T<T,N> tJunoStack;
);

#endif

template<typename T, const size_t N>
RESULT_T<T> Pop(STACK_T<T, N>& tStack)
{
    auto& tJunoStack = reinterpret_cast<JUNO_STACK_T<T, N>&>(tStack);
    RESULT_T<T> tResult{JUNO_STATUS_SUCCESS, {}};
    if(tJunoStack.tRoot.zLength > 0)
    {
        tJunoStack.tRoot.zLength -= 1;
        tResult.tSuccess = tJunoStack.ptArrBuff->tArr[tJunoStack.tRoot.zLength];
        return tResult;
    }
    tResult.tStatus = JUNO_STATUS_ERR;
    JUNO_FAIL(tResult.tStatus, tJunoStack.tRoot._pfcnFailureHandler, tJunoStack.tRoot._pvFailureUserData, "Stack is empty");
    return tResult;
}

template<typename T, const size_t N>
JUNO_STATUS_T Push(STACK_T<T, N>& tStack, T tData)
{
    auto& tJunoStack = reinterpret_cast<JUNO_STACK_T<T, N>&>(tStack);
    if(tJunoStack.tRoot.zLength < N)
    {
        tJunoStack.ptArrBuff->tArr[tJunoStack.tRoot.zLength] = tData;
        tJunoStack.tRoot.zLength += 1;
        return JUNO_STATUS_SUCCESS;
    }
    JUNO_FAIL(JUNO_STATUS_INVALID_SIZE_ERROR, tJunoStack.tRoot._pfcnFailureHandler, tJunoStack.tRoot._pvFailureUserData, "Stack is full");
    return JUNO_STATUS_INVALID_SIZE_ERROR;
}

template<typename T, const size_t N>
RESULT_T<T*> StackPeek(STACK_T<T, N>& tStack)
{
    auto& tJunoStack = reinterpret_cast<JUNO_STACK_T<T, N>&>(tStack);
    RESULT_T<T*> tResult{JUNO_STATUS_SUCCESS, {}};
    if(tJunoStack.tRoot.zLength > 0)
    {
        tResult.tSuccess = &tJunoStack.ptArrBuff->tArr[tJunoStack.tRoot.zLength];
        return tResult;
    }
    tResult.tStatus = JUNO_STATUS_ERR;
    JUNO_FAIL(tResult.tStatus, tJunoStack.tRoot._pfcnFailureHandler, tJunoStack.tRoot._pvFailureUserData, "Stack is empty");
    return tResult;
}



}
}

#endif // JUNO_BUFF_QUEUE_API_H
