/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
 * @file async_io_api.h
 * @brief Asynchronous/non-blocking IO facade with timeouts.
 * @defgroup juno_io_async Async IO API
 * @details
 *  Read/Write primitives with optional timeout. Size parameters are in/out:
 *  on input, they specify buffer capacity/desired length; on return, they are
 *  updated with the number of bytes read/written.
 */
#ifndef JUNO_ASYNC_IO_API_H
#define JUNO_ASYNC_IO_API_H
#include "juno/status.h"
#include "juno/module.h"
#include "juno/time/time_api.h"
#include <stdbool.h>
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_ASYNC_IO_API_TAG JUNO_ASYNC_IO_API_T;

typedef struct JUNO_ASYNC_IO_ROOT_TAG JUNO_ASYNC_IO_ROOT_T;

struct JUNO_ASYNC_IO_ROOT_TAG JUNO_MODULE_ROOT(JUNO_ASYNC_IO_API_T, JUNO_MODULE_EMPTY);

struct JUNO_ASYNC_IO_API_TAG
{
    /// @brief Read up to *pzBuffSize bytes; updates size with bytes read.
    JUNO_STATUS_T (*Read)(JUNO_ASYNC_IO_ROOT_T *ptIo, char *pcBuff, size_t *pzBuffSize);
    /// @brief Try to read with timeout; returns when data available or timeout.
    JUNO_STATUS_T (*TryRead)(JUNO_ASYNC_IO_ROOT_T *ptIo, char *pcBuff, size_t *pzBuffSize, JUNO_TIME_MICROS_T iTimeoutUs);
    /// @brief Read until any stop character is received (size updated).
    JUNO_STATUS_T (*ReadUntil)(JUNO_ASYNC_IO_ROOT_T *ptIo, char *pcBuff, size_t *pzBuffSize, const char *pcStopChars, size_t zSizeStopChars);
    /// @brief Try to read until stop character or timeout.
    JUNO_STATUS_T (*TryReadUntil)(JUNO_ASYNC_IO_ROOT_T *ptIo, char *pcBuff, size_t *pzBuffSize, const char *pcStopChars, size_t zSizeStopChars, JUNO_TIME_MICROS_T iTimeoutUs);
    /// @brief Write up to *pzBuffSize bytes; updates size with bytes written.
    JUNO_STATUS_T (*Write)(JUNO_ASYNC_IO_ROOT_T *ptIo, const void *pvBuff, size_t *pzBuffSize);
    /// @brief Try to write with timeout; updates size with bytes written.
    JUNO_STATUS_T (*TryWrite)(JUNO_ASYNC_IO_ROOT_T *ptIo, const void *pvBuff, size_t *pzBuffSize, JUNO_TIME_MICROS_T iTimeoutUs);
    /// @brief Poll for input readiness within timeout; sets pbHasData.
    JUNO_STATUS_T (*Poll)(JUNO_ASYNC_IO_ROOT_T *ptIo, JUNO_TIME_MICROS_T iTimeoutUs, bool *pbHasData);
};

#ifdef __cplusplus
}
#endif
#endif // JUNO_ASYNC_IO_API_H
