/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the io library API
    @author
*/
#ifndef JUNO_SPI_IO_API_H
#define JUNO_SPI_IO_API_H
#include "juno/status.h"
#include "juno/module.h"
#include "juno/time/time_api.h"
#include <stdbool.h>
#include <stdint.h>
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_SPI_IO_API_TAG JUNO_SPI_IO_API_T;
JUNO_MODULE_DECLARE(JUNO_SPI_IO_T);
JUNO_MODULE_BASE_DECLARE(JUNO_SPI_IO_BASE_T);

JUNO_MODULE_BASE(JUNO_SPI_IO_BASE_T, JUNO_SPI_IO_API_T, JUNO_MODULE_EMPTY);


struct JUNO_SPI_IO_API_TAG
{
    /// Perform an SPI transaction
    JUNO_STATUS_T (*Transaction)(JUNO_SPI_IO_T *ptIo, char *pcReadBuff, size_t zReadBuffSize, const void *pvWriteBuff, size_t zWriteBuffSize);
};

#ifdef __cplusplus
}
#endif
#endif // JUNO_SPI_IO_API_H
