/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
 * @file array_api.h
 * @brief Abstract array interface for DS modules.
 * @defgroup juno_ds_array Array API
 * @details
 *  A minimal fixed-capacity array abstraction used by other data structures
 *  (e.g., heaps and maps). Provides SetAt/GetAt/RemoveAt operations and
 *  verification helpers to ensure capacity and API validity.
 */
#ifndef JUNO_DS_ARRAY_API_H
#define JUNO_DS_ARRAY_API_H
#include "juno/macros.h"
#include "juno/memory/pointer_api.h"
#include "juno/status.h"
#include "juno/module.h"
#include <stddef.h>
#ifdef __cplusplus
extern "C"
{
#endif

/// @brief Opaque array root carrying capacity and API pointer.
typedef struct JUNO_DS_ARRAY_ROOT_TAG JUNO_DS_ARRAY_ROOT_T;
typedef struct JUNO_DS_ARRAY_API_TAG  JUNO_DS_ARRAY_API_T;

/// @brief Array root with capacity.
struct JUNO_DS_ARRAY_ROOT_TAG JUNO_MODULE_ROOT(JUNO_DS_ARRAY_API_T,
    /// The capacity of this array
    size_t zCapacity;
);

struct JUNO_DS_ARRAY_API_TAG
{
    /// @brief Set the value at an index.
    /// @return JUNO_STATUS_SUCCESS on success; JUNO_STATUS_OOB_ERROR on invalid index.
    JUNO_STATUS_T (*SetAt)(JUNO_DS_ARRAY_ROOT_T *ptArray, JUNO_POINTER_T tItem, size_t iIndex);
    /// @brief Get the value at an index.
    /// @return Result containing a pointer descriptor on success.
    JUNO_RESULT_POINTER_T (*GetAt)(JUNO_DS_ARRAY_ROOT_T *ptArray, size_t iIndex);
    /// @brief Remove a value at an index.
    /// @return JUNO_STATUS_SUCCESS on success; JUNO_STATUS_OOB_ERROR on invalid index.
    JUNO_STATUS_T (*RemoveAt)(JUNO_DS_ARRAY_ROOT_T *ptArray, size_t iIndex);
};

/**
 * @brief Verify that the array API provides all required functions.
 */
static inline JUNO_STATUS_T JunoDs_ArrayApiVerify(const JUNO_DS_ARRAY_API_T *ptArrayApi)
{
    JUNO_ASSERT_EXISTS(ptArrayApi);
    JUNO_ASSERT_EXISTS(
        ptArrayApi &&
        ptArrayApi->GetAt &&
        ptArrayApi->SetAt &&
        ptArrayApi->RemoveAt
    );
    return JUNO_STATUS_SUCCESS;
}
/**
 * @brief Verify an array instance's capacity and API.
 */
static inline JUNO_STATUS_T JunoDs_ArrayVerify(const JUNO_DS_ARRAY_ROOT_T *ptArray)
{
    JUNO_ASSERT_EXISTS(ptArray);
    JUNO_ASSERT_EXISTS(
        ptArray->zCapacity
    );
    JUNO_STATUS_T tStatus = JunoDs_ArrayApiVerify(ptArray->ptApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return tStatus;
}

/**
 * @brief Verify an index is within array capacity.
 * @return JUNO_STATUS_SUCCESS or JUNO_STATUS_OOB_ERROR (and invokes failure handler).
 */
static inline JUNO_STATUS_T JunoDs_ArrayVerifyIndex(const JUNO_DS_ARRAY_ROOT_T *ptArray, size_t iIndex)
{
    JUNO_STATUS_T tStatus = JunoDs_ArrayVerify(ptArray);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    if(iIndex >= ptArray->zCapacity)
    {
        tStatus = JUNO_STATUS_OOB_ERROR;
        JUNO_FAIL_ROOT(tStatus, ptArray, "Index is OOB");
    }
    return tStatus;
}

/**
 * @brief Initialize an array root with capacity and API.
 */
static inline JUNO_STATUS_T JunoDs_ArrayInit(JUNO_DS_ARRAY_ROOT_T *ptArray, const JUNO_DS_ARRAY_API_T *ptArrayApi, size_t iCapacity, JUNO_FAILURE_HANDLER_T pfcnFailureHdlr, JUNO_USER_DATA_T *pvUserData)
{
    JUNO_ASSERT_EXISTS(ptArray && iCapacity && ptArrayApi);
    ptArray->ptApi = ptArrayApi;
    ptArray->zCapacity = iCapacity;
    ptArray->_pfcnFailureHandler = pfcnFailureHdlr;
    ptArray->_pvFailureUserData = pvUserData;
    JUNO_STATUS_T tStatus = JunoDs_ArrayVerify(ptArray);
    return tStatus;
}

#ifdef __cplusplus
}
#endif
#endif // JUNO_DS_ARRAY_API_H

