/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_buff_queue library API
    @author Robin Onsay
*/
#ifndef JUNO_BUFF_QUEUE_API_H
#define JUNO_BUFF_QUEUE_API_H
#include "juno/macros.h"
#include "juno/status.h"
#include "juno/module.h"
#include "juno/types.h"
#include <stddef.h>
#ifdef __cplusplus
extern "C"
{
#endif

/// The Buffer queue root
typedef struct JUNO_BUFF_QUEUE_ROOT_TAG JUNO_BUFF_QUEUE_ROOT_T;
typedef struct JUNO_BUFF_QUEUE_API_TAG  JUNO_BUFF_QUEUE_API_T;
/// The Buffer queue module
typedef union JUNO_BUFF_QUEUE_T JUNO_BUFF_QUEUE_T;

/// The root buffee queue
struct JUNO_BUFF_QUEUE_ROOT_TAG JUNO_MODULE_ROOT(JUNO_BUFF_QUEUE_API_T,
    /// The start index of the buffer (ie the first element)
    size_t iStartIndex;
    /// The current length of the buffer
    size_t zLength;
    /// The capacity of the buffer
    size_t zCapacity;
);

struct JUNO_BUFF_QUEUE_API_TAG
{
    JUNO_STATUS_T (*SetAt)(JUNO_BUFF_QUEUE_T *ptQueue, void *ptItem, size_t iIndex);
    JUNO_RESULT_VOID_PTR_T (*GetAt)(JUNO_BUFF_QUEUE_T *ptQueue, size_t iIndex);
    JUNO_STATUS_T (*RemoveAt)(JUNO_BUFF_QUEUE_T *ptQueue, size_t iIndex);
    JUNO_STATUS_T (*Copy)(void *ptDest, void *ptSrc);
};

static inline JUNO_STATUS_T JunoDs_Buff_QueueVerify(JUNO_BUFF_QUEUE_ROOT_T *ptQueue)
{
    JUNO_ASSERT_EXISTS(ptQueue);
    JUNO_ASSERT_EXISTS(
        ptQueue->ptApi &&
        ptQueue->zCapacity && 
        ptQueue->ptApi->GetAt &&
        ptQueue->ptApi->SetAt &&
        ptQueue->ptApi->RemoveAt
    );
    return JUNO_STATUS_SUCCESS;
}

/// Initialize a buffer queue with a capacity
static inline JUNO_STATUS_T JunoDs_Buff_QueueInit(JUNO_BUFF_QUEUE_ROOT_T *ptQueue, const JUNO_BUFF_QUEUE_API_T *ptApi, size_t zCapacity, JUNO_FAILURE_HANDLER_T pfcnFailureHdlr, JUNO_USER_DATA_T *pvFailureUserData)
{
    JUNO_ASSERT_EXISTS(ptQueue);
    ptQueue->ptApi = ptApi;
    ptQueue->iStartIndex = 0;
    ptQueue->zLength = 0;
    ptQueue->zCapacity = zCapacity;
    ptQueue->_pfcnFailureHandler = pfcnFailureHdlr;
    ptQueue->_pvFailureUserData = pvFailureUserData;
    return JunoDs_Buff_QueueVerify(ptQueue);
}

/// Enqueue an item into the buffer
/// @returns The index to place the enqueued item
static inline JUNO_STATUS_T JunoDs_Buff_QueueEnqueue(JUNO_BUFF_QUEUE_ROOT_T *ptQueue, void *ptItem)
{
    JUNO_ASSERT_EXISTS(ptQueue);
    JUNO_STATUS_T tStatus = JunoDs_Buff_QueueVerify(ptQueue);
    if(ptQueue->zLength < ptQueue->zCapacity)
    {
        size_t iIndex = (ptQueue->iStartIndex + ptQueue->zLength) % ptQueue->zCapacity;
        tStatus = ptQueue->ptApi->SetAt((JUNO_BUFF_QUEUE_T *) ptQueue, ptItem, iIndex);
        JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
        ptQueue->zLength += 1;
    }
    else
    {
        tStatus = JUNO_STATUS_INVALID_SIZE_ERROR;
        JUNO_FAIL(tStatus, ptQueue->_pfcnFailureHandler, ptQueue->_pvFailureUserData, "Failed to enqueue data");
        return tStatus;
    }
    return tStatus;
}

/// Dequeue an item from the buffer
/// @returns The index to dequeue the item from
static inline JUNO_STATUS_T JunoDs_Buff_QueueDequeue(JUNO_BUFF_QUEUE_ROOT_T *ptQueue, void *ptReturn)
{
    JUNO_STATUS_T tStatus = JunoDs_Buff_QueueVerify(ptQueue);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    JUNO_ASSERT_EXISTS(ptReturn);
    if(ptQueue->zLength > 0)
    {
        const JUNO_BUFF_QUEUE_API_T *ptApi = ptQueue->ptApi;
        size_t iDequeueIndex = ptQueue->iStartIndex;
        JUNO_RESULT_VOID_PTR_T tPtrResult = ptApi->GetAt((JUNO_BUFF_QUEUE_T *) ptQueue, iDequeueIndex);
        JUNO_ASSERT_SUCCESS(tPtrResult.tStatus, return tPtrResult.tStatus);
        tStatus = ptApi->Copy(ptReturn, JUNO_OK(tPtrResult));
        JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
        tStatus = ptApi->RemoveAt((JUNO_BUFF_QUEUE_T *) ptQueue, iDequeueIndex);
        JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
        ptQueue->iStartIndex = (ptQueue->iStartIndex + 1) % ptQueue->zCapacity;
        ptQueue->zLength -= 1;
        return tStatus;
    }
    tStatus = JUNO_STATUS_ERR;
    JUNO_FAIL(tStatus, ptQueue->_pfcnFailureHandler, ptQueue->_pvFailureUserData, "Queue is empty");
    return tStatus;
}

/// Peek at the next item in the queue
/// @returns the index of the next item in the queue
static inline JUNO_RESULT_VOID_PTR_T JunoBuff_QueuePeek(JUNO_BUFF_QUEUE_ROOT_T *ptQueue)
{
    JUNO_RESULT_VOID_PTR_T tResult = JUNO_ERR_RESULT(JUNO_STATUS_ERR, NULL);
    tResult.tStatus = JunoDs_Buff_QueueVerify(ptQueue);
    JUNO_ASSERT_SUCCESS(tResult.tStatus, return tResult);
    if(ptQueue->zLength == 0)
    {
        tResult.tStatus = JUNO_STATUS_INVALID_SIZE_ERROR;
        JUNO_FAIL(tResult.tStatus, ptQueue->_pfcnFailureHandler, ptQueue->_pvFailureUserData, "Queue is empty");
        return tResult;
    }
    tResult = ptQueue->ptApi->GetAt((JUNO_BUFF_QUEUE_T *) ptQueue, ptQueue->iStartIndex);
    return tResult;
}


#ifdef __cplusplus
}
#endif
#endif // JUNO_BUFF_QUEUE_API_H
