/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_buff_queue library API
    @author Robin Onsay
*/
#ifndef JUNO_BUFF_QUEUE_API_H
#define JUNO_BUFF_QUEUE_API_H
#include "juno/ds/array_api.h"
#include "juno/macros.h"
#include "juno/memory/pointer_api.h"
#include "juno/status.h"
#include "juno/module.h"
#include <stddef.h>
#ifdef __cplusplus
extern "C"
{
#endif

/// The Buffer queue root
typedef struct JUNO_BUFF_QUEUE_ROOT_TAG JUNO_BUFF_QUEUE_ROOT_T;
typedef struct JUNO_BUFF_QUEUE_API_TAG  JUNO_BUFF_QUEUE_API_T;

/// The root buffee queue
struct JUNO_BUFF_QUEUE_ROOT_TAG JUNO_MODULE_ROOT(JUNO_BUFF_QUEUE_API_T,
    JUNO_ARRAY_ROOT_T *ptBuffer;
    /// The start index of the buffer (ie the first element)
    size_t iStartIndex;
);

struct JUNO_BUFF_QUEUE_API_TAG
{
    /// Enqueue an item on the queue
    JUNO_STATUS_T (*Enqueue)(JUNO_BUFF_QUEUE_ROOT_T *ptQueue, JUNO_POINTER_T tItem);
    /// Dequeue an item from the queue
    JUNO_STATUS_T (*Dequeue)(JUNO_BUFF_QUEUE_ROOT_T *ptQueue, JUNO_POINTER_T tReturn);
    /// Peek at the next item in the queue
    JUNO_RESULT_POINTER_T (*Peek)(JUNO_BUFF_QUEUE_ROOT_T *ptQueue);
};

static inline JUNO_STATUS_T JunoDs_Buff_QueueApiVerify(const JUNO_BUFF_QUEUE_API_T *ptQueueApi)
{
     JUNO_ASSERT_EXISTS(
        ptQueueApi &&
        ptQueueApi->Enqueue &&
        ptQueueApi->Dequeue &&
        ptQueueApi->Peek
    );
    return JUNO_STATUS_SUCCESS;   
}

static inline JUNO_STATUS_T JunoDs_Buff_QueueVerify(const JUNO_BUFF_QUEUE_ROOT_T *ptQueue)
{
    JUNO_ASSERT_EXISTS(ptQueue);
    JUNO_STATUS_T tStatus = JunoDs_ArrayVerify(ptQueue->ptBuffer);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return JunoDs_Buff_QueueApiVerify(ptQueue->ptApi);
}

/// Initialize a buffer queue with a capacity
JUNO_STATUS_T JunoDs_Buff_QueueInit(JUNO_BUFF_QUEUE_ROOT_T *ptQueue, JUNO_ARRAY_ROOT_T *ptBuffer, JUNO_FAILURE_HANDLER_T pfcnFailureHdlr, JUNO_USER_DATA_T *pvFailureUserData);

#ifdef __cplusplus
}
#endif
#endif // JUNO_BUFF_QUEUE_API_H
