/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_buff_stack library API
    @author Robin Onsay
*/
#ifndef JUNO_BUFF_STACK_API_H
#define JUNO_BUFF_STACK_API_H
#include "juno/macros.h"
#include "juno/status.h"
#include "juno/module.h"
#include "juno/types.h"
#ifdef __cplusplus
extern "C"
{
#endif

/// The buffer stack root module
typedef struct JUNO_BUFF_STACK_ROOT_TAG JUNO_BUFF_STACK_ROOT_T;
typedef struct JUNO_BUFF_STACK_API_TAG JUNO_BUFF_STACK_API_T;

struct JUNO_BUFF_STACK_ROOT_TAG JUNO_MODULE_ROOT(JUNO_BUFF_STACK_API_T,
    /// The current length of the stack
    size_t zLength;
    /// The capacity of the stack
    size_t zCapacity;
);

struct JUNO_BUFF_STACK_API_TAG
{
    JUNO_STATUS_T (*SetAt)(JUNO_BUFF_STACK_ROOT_T *ptStack, void *ptItem, size_t iIndex);
    JUNO_RESULT_VOID_PTR_T (*GetAt)(JUNO_BUFF_STACK_ROOT_T *ptStack, size_t iIndex);
    JUNO_STATUS_T (*RemoveAt)(JUNO_BUFF_STACK_ROOT_T *ptStack, size_t iIndex);
    JUNO_STATUS_T (*Copy)(void *ptDest, void *ptSrc);
};

static inline JUNO_STATUS_T JunoDs_Buff_StackVerify(JUNO_BUFF_STACK_ROOT_T *ptStack)
{
    JUNO_ASSERT_EXISTS(ptStack);
    JUNO_ASSERT_EXISTS(
        ptStack->ptApi &&
        ptStack->zCapacity && 
        ptStack->ptApi->GetAt &&
        ptStack->ptApi->SetAt &&
        ptStack->ptApi->RemoveAt &&
        ptStack->ptApi->Copy
    );
    return JUNO_STATUS_SUCCESS;
}

/// Initialize a buffer queue with a capacity
JUNO_STATUS_T JunoDs_Buff_StackInit(JUNO_BUFF_STACK_ROOT_T *ptQueue, const JUNO_BUFF_STACK_API_T *ptApi, size_t zCapacity, JUNO_FAILURE_HANDLER_T pfcnFailureHdlr, JUNO_USER_DATA_T *pvFailureUserData);

/// Enqueue an item into the buffer
/// @returns The index to place the enqueued item
JUNO_STATUS_T JunoDs_Buff_StackPush(JUNO_BUFF_STACK_ROOT_T *ptQueue, void *ptItem);


/// Dequeue an item from the buffer
/// @returns The index to dequeue the item from
JUNO_STATUS_T JunoDs_Buff_StackPop(JUNO_BUFF_STACK_ROOT_T *ptQueue, void *ptReturn);


/// Peek at the next item in the queue
/// @returns the index of the next item in the queue
JUNO_RESULT_VOID_PTR_T JunoDs_Buff_StackPeek(JUNO_BUFF_STACK_ROOT_T *ptQueue);

#ifdef __cplusplus
}
#endif
#endif // JUNO_BUFF_STACK_API_H
