/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
 * @file map_api.h
 * @brief Hash map API built on array and pointer traits.
 * @defgroup juno_ds_map Map API
 * @details
 *  An associative container interface parameterized by a hash function and a
 *  value-equality comparator. Backed by a user-supplied array for storage.
 */
#ifndef JUNO_MAP_API_H
#define JUNO_MAP_API_H
#include "juno/ds/array_api.h"
#include "juno/macros.h"
#include "juno/memory/pointer_api.h"
#include "juno/module.h"
#include <stdbool.h>
#include <stddef.h>
#include "juno/status.h"
#include "juno/types.h"
#ifdef __cplusplus
extern "C"
{
#endif
typedef struct JUNO_MAP_API_TAG JUNO_MAP_API_T;
typedef struct JUNO_MAP_ROOT_TAG JUNO_MAP_ROOT_T;
typedef struct JUNO_MAP_HASHABLE_POINTER_API_TAG JUNO_MAP_HASHABLE_POINTER_API_T;
struct JUNO_MAP_ROOT_TAG JUNO_MODULE_ROOT(JUNO_MAP_API_T,
    const JUNO_MAP_HASHABLE_POINTER_API_T *ptHashablePointerApi;
    const JUNO_VALUE_POINTER_API_T *ptValuePointerApi;
    JUNO_DS_ARRAY_ROOT_T *ptHashMap;
);

/** @brief Hashing and null-check operations for map keys/values. */
struct JUNO_MAP_HASHABLE_POINTER_API_TAG
{
    /// @brief Compute a hash value for the given key.
    JUNO_RESULT_SIZE_T (*Hash)(JUNO_POINTER_T tItem);
    /// @brief Determine if a value slot is logically empty/null.
    JUNO_RESULT_BOOL_T (*IsValueNull)(JUNO_POINTER_T tItem);
};

struct JUNO_MAP_API_TAG
{
    /// @brief Retrieve the value for the provided key; returns pointer result.
    JUNO_RESULT_POINTER_T (*Get)(JUNO_MAP_ROOT_T *ptJunoMap, JUNO_POINTER_T tReturnItem);
    /// @brief Insert or update a key-value pair.
    JUNO_STATUS_T (*Set)(JUNO_MAP_ROOT_T *ptJunoMap, JUNO_POINTER_T tItem);
    /// @brief Remove a key (and its value) from the map.
    JUNO_STATUS_T (*Remove)(JUNO_MAP_ROOT_T *ptJunoMap, JUNO_POINTER_T tKey);
};

/// Verify the map has all members
static inline JUNO_STATUS_T JunoDs_MapVerify(JUNO_MAP_ROOT_T *ptMap)
{
    JUNO_ASSERT_EXISTS(
        ptMap &&
        ptMap->ptApi &&
        ptMap->ptHashablePointerApi &&
        ptMap->ptValuePointerApi &&
        ptMap->ptHashMap &&
        ptMap->ptHashablePointerApi->Hash &&
        ptMap->ptHashablePointerApi->IsValueNull &&
        ptMap->ptValuePointerApi->Equals
    );
    JUNO_STATUS_T tStatus = JunoDs_ArrayVerify(ptMap->ptHashMap);
    return tStatus;
}

/// @brief Initialize the map root with hashing and equality APIs and backing array.
JUNO_STATUS_T JunoDs_MapInit(JUNO_MAP_ROOT_T *ptMapRoot, const JUNO_MAP_HASHABLE_POINTER_API_T *ptHashablePointerApi, const JUNO_VALUE_POINTER_API_T *ptValuePointerApi, JUNO_DS_ARRAY_ROOT_T *ptArray, JUNO_FAILURE_HANDLER_T pfcnFailureHandler, JUNO_USER_DATA_T *pvUserData);
/// Get/Set/Remove operations
JUNO_RESULT_POINTER_T JunoDs_MapGet(JUNO_MAP_ROOT_T *ptJunoMap, JUNO_POINTER_T tItem);
JUNO_STATUS_T JunoDs_MapSet(JUNO_MAP_ROOT_T *ptJunoMap, JUNO_POINTER_T tItem);
JUNO_STATUS_T JunoDs_MapRemove(JUNO_MAP_ROOT_T *ptJunoMap, JUNO_POINTER_T tKey);
#ifdef __cplusplus
}
#endif
#endif // JUNO_MAP_API_H
