/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_map library API
    @author Robin Onsay
*/
#ifndef JUNO_MAP_API_H
#define JUNO_MAP_API_H
#include "juno/macros.h"
#include "juno/module.h"
#include <stdbool.h>
#include <stddef.h>
#include "juno/status.h"
#include "juno/types.h"
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_MAP_API_TAG JUNO_MAP_API_T;

typedef struct JUNO_MAP_ROOT_TAG JUNO_MAP_ROOT_T;

struct JUNO_MAP_ROOT_TAG JUNO_MODULE_ROOT(JUNO_MAP_API_T,
    /// The capacity of the hash map
    size_t zCapacity;
);


struct JUNO_MAP_API_TAG
{
    /// Calculate the hash for the given key
    JUNO_RESULT_SIZE_T (*Hash)(void *ptKey);
    /// Return true if the left and right are equal
    JUNO_RESULT_BOOL_T (*KeyIsEqual)(void *ptLeft, void *ptRight);
    /// Get the value at the given index
    JUNO_RESULT_VOID_PTR_T (*GetValue)(size_t iIndex);
    /// Get the key at the given index
    JUNO_RESULT_VOID_PTR_T (*GetKey)(size_t iIndex);
    /// Set the value at the given index
    JUNO_STATUS_T (*SetValue)(size_t iIndex, void *ptValue);
    /// Set the key at the given index
    JUNO_STATUS_T (*SetKey)(size_t iIndex, void *ptKey);
    /// Remove the key and value at the given index
    JUNO_STATUS_T (*Remove)(size_t iIndex);
    /// Check if the given index is empty
    JUNO_RESULT_BOOL_T (*IsEmpty)(size_t zIndex);
};

/// Check if the api has all members
static inline JUNO_STATUS_T JunoMap_VerifyApi(const JUNO_MAP_API_T *ptApi)
{
    JUNO_ASSERT_EXISTS(
        ptApi &&
        ptApi->Hash && 
        ptApi->KeyIsEqual && 
        ptApi->GetValue &&
        ptApi->GetKey &&
        ptApi->SetValue &&
        ptApi->SetKey &&
        ptApi->Remove &&
        ptApi->IsEmpty
    );
    return JUNO_STATUS_SUCCESS;
}

/// Verify the map has all members
static inline JUNO_STATUS_T JunoMap_Verify(JUNO_MAP_ROOT_T *ptMap)
{
    JUNO_ASSERT_EXISTS(ptMap);
    JUNO_STATUS_T tStatus = JunoMap_VerifyApi(ptMap->ptApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    JUNO_ASSERT_EXISTS(ptMap->zCapacity);
    return tStatus;
}

/// Get the index for a given key
JUNO_RESULT_SIZE_T JunoMap_GetIndex(JUNO_MAP_ROOT_T *ptJunoMap, void *ptKey);

/// Set the value at a given key
static inline JUNO_STATUS_T JunoMap_Set(JUNO_MAP_ROOT_T *ptJunoMap, void *ptKey, void *ptValue)
{
    // verify the map
    JUNO_STATUS_T tStatus = JunoMap_Verify(ptJunoMap);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    // Get the index for the key
    JUNO_RESULT_SIZE_T tSizeResult = JunoMap_GetIndex(ptJunoMap, ptKey);
    tStatus = tSizeResult.tStatus;
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    // Set the key for the index
    tStatus = ptJunoMap->ptApi->SetKey(tSizeResult.tOk, ptKey);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    // Set the value for the index
    tStatus = ptJunoMap->ptApi->SetValue(tSizeResult.tOk, ptValue);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return tStatus;
}

/// Get the value for a given key
static inline JUNO_RESULT_VOID_PTR_T JunoMap_Get(JUNO_MAP_ROOT_T *ptJunoMap, void *ptKey)
{
    JUNO_RESULT_VOID_PTR_T tResult = {0, NULL};
    tResult.tStatus = JunoMap_Verify(ptJunoMap);
    JUNO_ASSERT_SUCCESS(tResult.tStatus, return tResult);
    // Get the index for the key
    JUNO_RESULT_SIZE_T tSizeResult = JunoMap_GetIndex(ptJunoMap, ptKey);
    tResult.tStatus = tSizeResult.tStatus;
    JUNO_ASSERT_SUCCESS(tResult.tStatus, return tResult);
    // Check if the value at the index is empty
    JUNO_RESULT_BOOL_T tBoolResult = ptJunoMap->ptApi->IsEmpty(tSizeResult.tOk);
    tResult.tStatus = tBoolResult.tStatus;
    JUNO_ASSERT_SUCCESS(tResult.tStatus, return tResult);
    bool bIsEmpty = tBoolResult.tOk;
    if(bIsEmpty)
    {
        // Its empty so return DNE error
        tResult.tStatus = JUNO_STATUS_DNE_ERROR;
        return tResult;
    }
    // Get the value
    return ptJunoMap->ptApi->GetValue(tSizeResult.tOk);
}

/// Remove the key and value ata given key
static inline JUNO_STATUS_T JunoMap_Remove(JUNO_MAP_ROOT_T *ptJunoMap, void *ptKey)
{
    JUNO_STATUS_T tStatus = JunoMap_Verify(ptJunoMap);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    // Get the index for the given key
    JUNO_RESULT_SIZE_T tSizeResult = JunoMap_GetIndex(ptJunoMap, ptKey);
    tStatus = tSizeResult.tStatus;
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    // Check if the key is empty
    JUNO_RESULT_BOOL_T tBoolResult = ptJunoMap->ptApi->IsEmpty(tSizeResult.tOk);
    tStatus = tBoolResult.tStatus;
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    bool bIsEmpty = tBoolResult.tOk;
    if(bIsEmpty)
    {
        // Its empty so fail silently
        return tStatus;
    }
    //  Remove the key, value at the index
    tStatus = ptJunoMap->ptApi->Remove(tSizeResult.tOk);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return tStatus;
}

#ifdef __cplusplus
}
#endif
#endif // JUNO_MAP_API_H
