/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_map library API
    @author Robin Onsay
*/
#ifndef JUNO_MAP_API_H
#define JUNO_MAP_API_H
#include "juno/macros.h"
#include "juno/module.h"
#include <stdbool.h>
#include <stddef.h>
#include "juno/status.h"
#include "juno/types.h"
#include "juno/memory/memory_api.h"
#ifdef __cplusplus
extern "C"
{
#endif

typedef struct JUNO_MAP_BUFFER_API_TAG JUNO_MAP_BUFFER_API_T;
typedef struct JUNO_MAP_API_TAG JUNO_MAP_API_T;

typedef struct JUNO_MAP_ROOT_TAG JUNO_MAP_ROOT_T;

struct JUNO_MAP_ROOT_TAG JUNO_MODULE_ROOT(JUNO_MAP_API_T,
    /// The capacity of the hash map
    const JUNO_MAP_BUFFER_API_T *ptBufferApi;
    size_t zCapacity;
);


struct JUNO_MAP_BUFFER_API_TAG
{
    /// Calculate the hash for the given key
    JUNO_RESULT_SIZE_T (*Hash)(JUNO_POINTER_T tKey);
    /// Return true if the left and right are equal
    JUNO_RESULT_BOOL_T (*KeyIsEqual)(JUNO_POINTER_T tLeft, JUNO_POINTER_T tRight);
    /// Get the value at the given index
    JUNO_RESULT_POINTER_T (*GetValue)(size_t iIndex);
    /// Get the key at the given index
    JUNO_RESULT_POINTER_T (*GetKey)(size_t iIndex);
    /// Set the value at the given index
    JUNO_STATUS_T (*SetValue)(size_t iIndex, JUNO_POINTER_T tValue);
    /// Set the key at the given index
    JUNO_STATUS_T (*SetKey)(size_t iIndex, JUNO_POINTER_T tKey);
    /// Remove the key and value at the given index
    JUNO_STATUS_T (*Remove)(size_t iIndex);
    /// Check if the given index is empty
    JUNO_RESULT_BOOL_T (*IsEmpty)(size_t zIndex);
};

struct JUNO_MAP_API_TAG
{

    JUNO_RESULT_POINTER_T (*Get)(JUNO_MAP_ROOT_T *ptJunoMap, JUNO_POINTER_T tKey);
    JUNO_STATUS_T (*Set)(JUNO_MAP_ROOT_T *ptJunoMap, JUNO_POINTER_T tKey, JUNO_POINTER_T tValue);
    JUNO_STATUS_T (*Remove)(JUNO_MAP_ROOT_T *ptJunoMap, JUNO_POINTER_T tKey);
};

/// Check if the api has all members
static inline JUNO_STATUS_T JunoMap_BufferApiVerify(const JUNO_MAP_BUFFER_API_T *ptApi)
{
    JUNO_ASSERT_EXISTS(
        ptApi &&
        ptApi->Hash && 
        ptApi->KeyIsEqual && 
        ptApi->GetValue &&
        ptApi->GetKey &&
        ptApi->SetValue &&
        ptApi->SetKey &&
        ptApi->Remove &&
        ptApi->IsEmpty
    );
    return JUNO_STATUS_SUCCESS;
}

static inline JUNO_STATUS_T JunoMap_ApiVerify(const JUNO_MAP_API_T *ptApi)
{
    JUNO_ASSERT_EXISTS(
        ptApi &&
        ptApi->Get &&
        ptApi->Remove &&
        ptApi->Set
    );
    return JUNO_STATUS_SUCCESS;
}

/// Verify the map has all members
static inline JUNO_STATUS_T JunoMap_Verify(JUNO_MAP_ROOT_T *ptMap)
{
    JUNO_ASSERT_EXISTS(ptMap);
    JUNO_STATUS_T tStatus = JunoMap_BufferApiVerify(ptMap->ptBufferApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    tStatus = JunoMap_ApiVerify(ptMap->ptApi);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    JUNO_ASSERT_EXISTS(ptMap->zCapacity);
    return tStatus;
}

/// Get the index for a given key
JUNO_RESULT_SIZE_T JunoMap_GetIndex(JUNO_MAP_ROOT_T *ptJunoMap, JUNO_POINTER_T tKey);

/// Init the juno map module
JUNO_STATUS_T JunoMap_Init(JUNO_MAP_ROOT_T *ptMapRoot, const JUNO_MAP_BUFFER_API_T *ptBufferApi, size_t zCapacity, JUNO_FAILURE_HANDLER_T pfcnFailureHandler, JUNO_USER_DATA_T *pvUserData);
#ifdef __cplusplus
}
#endif
#endif // JUNO_MAP_API_H
