/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_ds_queue library API
    @author Robin Onsay
*/
#ifndef JUNO_DS_QUEUE_API_H
#define JUNO_DS_QUEUE_API_H
#include "juno/ds/array_api.h"
#include "juno/macros.h"
#include "juno/memory/pointer_api.h"
#include "juno/status.h"
#include "juno/module.h"
#include <stddef.h>
#ifdef __cplusplus
extern "C"
{
#endif

/// The Buffer queue root
typedef struct JUNO_DS_QUEUE_TAG JUNO_DS_QUEUE_T;
typedef struct JUNO_DS_QUEUE_API_TAG  JUNO_DS_QUEUE_API_T;

/// The root buffee queue
struct JUNO_DS_QUEUE_TAG JUNO_MODULE_DERIVE_WITH_API(JUNO_DS_ARRAY_ROOT_T, JUNO_DS_QUEUE_API_T,
    /// The start index of the buffer (ie the first element)
    size_t iStartIndex;
    /// The current length of the buffer
    size_t zLength;
);

struct JUNO_DS_QUEUE_API_TAG JUNO_MODULE_API_DERIVE(JUNO_DS_ARRAY_API_T,
    /// Enqueue an item on the queue
    JUNO_STATUS_T (*Enqueue)(JUNO_DS_QUEUE_T *ptQueue, JUNO_POINTER_T tItem);
    /// Dequeue an item from the queue
    JUNO_STATUS_T (*Dequeue)(JUNO_DS_QUEUE_T *ptQueue, JUNO_POINTER_T tReturn);
    /// Peek at the next item in the queue
    JUNO_RESULT_POINTER_T (*Peek)(JUNO_DS_QUEUE_T *ptQueue);
);

static inline JUNO_STATUS_T JunoDs_QueueApiVerify(const JUNO_DS_QUEUE_API_T *ptQueueApi)
{
     JUNO_ASSERT_EXISTS(
        ptQueueApi &&
        ptQueueApi->Enqueue &&
        ptQueueApi->Dequeue &&
        ptQueueApi->Peek
    );
    return JUNO_STATUS_SUCCESS;   
}

static inline JUNO_STATUS_T JunoDs_QueueVerify(const JUNO_DS_QUEUE_T *ptQueue)
{
    JUNO_ASSERT_EXISTS(ptQueue);
    JUNO_STATUS_T tStatus = JunoDs_ArrayVerify(&ptQueue->tRoot);
    JUNO_ASSERT_SUCCESS(tStatus, return tStatus);
    return JunoDs_QueueApiVerify(ptQueue->ptApi);
}

/// Enqueue an item on the queue
JUNO_STATUS_T JunoDs_QueuePush(JUNO_DS_QUEUE_T *ptQueue, JUNO_POINTER_T tItem);
/// Dequeue an item from the queue
JUNO_STATUS_T JunoDs_QueuePop(JUNO_DS_QUEUE_T *ptQueue, JUNO_POINTER_T tReturn);
/// Peek at the next item in the queue
JUNO_RESULT_POINTER_T JunoDs_QueuePeek(JUNO_DS_QUEUE_T *ptQueue);

#define JunoDs_QueueApiInit(...) { \
    {__VA_ARGS__}, \
    JunoDs_QueuePush, \
    JunoDs_QueuePop, \
    JunoDs_QueuePeek, \
}

/// Initialize a buffer queue with a capacity
JUNO_STATUS_T JunoDs_QueueInit(JUNO_DS_QUEUE_T *ptQueue, const JUNO_DS_QUEUE_API_T *ptQueueApi, size_t iCapacity, JUNO_FAILURE_HANDLER_T pfcnFailureHdlr, JUNO_USER_DATA_T *pvFailureUserData);

#ifdef __cplusplus
}
#endif
#endif // JUNO_DS_QUEUE_API_H
