/*
    MIT License

    Copyright (c) 2025 Robin A. Onsay

    Permission is hereby granted, free of charge, to any person obtaining
    a copy of this software and associated documentation files
    (the "Software"), to deal in the Software without restriction,
    including without limitation the rights to use, copy, modify, merge,
    publish, distribute, sublicense, and/or sell copies of the Software,
    and to permit persons to whom the Software is furnished to do so,
    subject to the following conditions:

    The above copyright notice and this permission notice shall be
    included in all copies or substantial portions of the Software.
*/

/**
    This API has been generated by LibJuno:
    https://www.robinonsay.com/libjuno/
*/

/**
    This header contains the juno_ds_stack library API
    @author Robin Onsay
*/
#ifndef JUNO_DS_STACK_API_H
#define JUNO_DS_STACK_API_H
#include "juno/ds/array_api.h"
#include "juno/macros.h"
#include "juno/memory/memory_api.h"
#include "juno/status.h"
#include "juno/module.h"
#include "juno/types.h"
#ifdef __cplusplus
extern "C"
{
#endif

/// The buffer stack root module
typedef struct JUNO_DS_STACK_ROOT_TAG JUNO_DS_STACK_ROOT_T;
typedef struct JUNO_DS_STACK_API_TAG JUNO_DS_STACK_API_T;

struct JUNO_DS_STACK_ROOT_TAG JUNO_MODULE_DERIVE_WITH_API(JUNO_DS_ARRAY_ROOT_T, JUNO_DS_STACK_API_T,
    /// The current length of the buffer
    size_t zLength;
);

struct JUNO_DS_STACK_API_TAG JUNO_MODULE_API_DERIVE(JUNO_DS_ARRAY_API_T,
    /// Enqueue an item into the buffer
    /// @returns The index to place the enqueued item
    JUNO_STATUS_T (*Push)(JUNO_DS_STACK_ROOT_T *ptQueue, JUNO_POINTER_T tItem);
    /// Dequeue an item from the buffer
    /// @returns The index to dequeue the item from
    JUNO_STATUS_T (*Pop)(JUNO_DS_STACK_ROOT_T *ptQueue, JUNO_POINTER_T tReturn);
    /// Peek at the next item in the queue
    /// @returns the index of the next item in the queue
    JUNO_RESULT_POINTER_T (*Peek)(JUNO_DS_STACK_ROOT_T *ptQueue);
);

#define JunoDs_StackApiInit(...) { \
    {__VA_ARGS__}, \
    JunoDs_StackPush, \
    JunoDs_StackPop, \
    JunoDs_StackPeek, \
}

static inline JUNO_STATUS_T JunoDs_StackVerify(const JUNO_DS_STACK_ROOT_T *ptStack)
{
    JUNO_ASSERT_EXISTS(ptStack);
    JUNO_ASSERT_EXISTS(
        ptStack->ptApi &&
        ptStack->ptApi->Push &&
        ptStack->ptApi->Pop &&
        ptStack->ptApi->Peek
    );
    return JunoDs_ArrayVerify(&ptStack->tRoot);
}

/// Initialize a buffer queue with a capacity
JUNO_STATUS_T JunoDs_StackInit(JUNO_DS_STACK_ROOT_T *ptStack, const JUNO_DS_STACK_API_T *ptStackApi, size_t iCapacity, JUNO_FAILURE_HANDLER_T pfcnFailureHdlr, JUNO_USER_DATA_T *pvFailureUserData);
JUNO_STATUS_T JunoDs_StackPush(JUNO_DS_STACK_ROOT_T *ptStack, JUNO_POINTER_T tItem);
JUNO_STATUS_T JunoDs_StackPop(JUNO_DS_STACK_ROOT_T *ptQueue, JUNO_POINTER_T tReturn);
JUNO_RESULT_POINTER_T JunoDs_StackPeek(JUNO_DS_STACK_ROOT_T *ptStack);



#ifdef __cplusplus
}
#endif
#endif // JUNO_DS_STACK_API_H
