name: Build and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  build-and-test:
    # matrix.job lets us run the same steps with different compilers
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # you can add macos-latest and windows-latest here if desired
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            cc: gcc-9
            cxx: g++-9
          - os: ubuntu-latest
            cc: gcc-11
            cxx: g++-11
          - os: ubuntu-latest
            cc: clang-10
            cxx: clang++-10
          - os: ubuntu-latest
            cc: clang-14
            cxx: clang++-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install compiler ${{ matrix.cc }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.cc }} ${{ matrix.cxx }}

      - name: Configure project with CMake
        run: |
          # force CMake to pick our matrix compiler
          CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} \
            cmake -B build . -DJUNO_TESTS=On -DJUNO_COVERAGE=On

      - name: Build project
        run: make -C build

      - name: Run CTest unit tests
        run: cd build && ctest --output-on-failure

      - name: Configure python
        run: pip install -r requirements.txt

      - name: Generate the coverage report using gcovr
        run: |
          mkdir -p coverage_report
          gcovr -r . --html --html-details -o coverage_report/coverage.html

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_report

